// This file was auto-generated by scripts/generate-test-utils.ts
// Do not edit this file directly

import KsqldbClient from 'ksqldb-client';

import { mapValues, mapKeys, isObject, isArray } from 'lodash';

export const sleep = (ms: number) =>
  new Promise((resolve) => setTimeout(resolve, ms));

export function escapeKeysDeep(obj: Record<string, any>): Record<string, any> {
  const escapeKey = (_: any, key: string) => {
    return `\`${key}\``;
  };

  if (isArray(obj)) {
    return obj.map((innerObj) => escapeKeysDeep(innerObj));
  } else if (isObject(obj)) {
    return mapValues(mapKeys(obj, escapeKey), (val) => escapeKeysDeep(val));
  } else {
    return obj;
  }
}

function isLowerCase(str: string) {
  return str === str.toLowerCase() && str !== str.toUpperCase();
}

export type TableSchemas = {
  ESDB_ASSET_CLASS: {
    asset_id: string | null;

    class?: {
      id?: string | null;
      name?: string | null;
      description?: string | null;
    };
  };

  ESDB_ASSET_COMPANY: {
    asset_id: string | null;

    company?: {
      id?: string | null;
      name?: string | null;
    };
  };

  ESDB_ASSET_GROUPS: {
    asset_id: string | null;

    groups?: Array<{
      id?: string | null;
      name?: string | null;
      company_id?: string | null;
      company_name?: string | null;
    }>;
  };

  ESDB_ASSET_INVENTORY_BRANCH: {
    asset_id: string | null;

    branch?: {
      id?: string | null;
      name?: string | null;
      description?: string | null;
      company_id?: string | null;
      company_name?: string | null;
    };
  };

  ESDB_ASSET_KEYPADS: {
    asset_id: string | null;

    data?: Array<string | null>;
  };

  ESDB_ASSET_KEYPADS_TABLE: {
    keypad_id: string | null;

    asset_id?: string | null;
  };

  ESDB_ASSET_MAKE: {
    asset_id: string | null;

    make?: {
      id?: string | null;
      name?: string | null;
    };
  };

  ESDB_ASSET_MATERIALIZED_VIEW: {
    asset_id: string | null;

    details?: {
      asset_id?: string | null;
      name?: string | null;
      description?: string | null;
      custom_name?: string | null;
      model?: string | null;
      year?: string | null;
      tracker_id?: string | null;
      vin?: string | null;
      serial_number?: string | null;
      driver_name?: string | null;
      camera_id?: string | null;
      photo_id?: string | null;
    };
    photo?: {
      photo_id?: string | null;
      filename?: string | null;
    };
    company?: {
      id?: string | null;
      name?: string | null;
    };
    type?: {
      id?: string | null;
      name?: string | null;
    };
    make?: {
      id?: string | null;
      name?: string | null;
    };
    model?: {
      id?: string | null;
      name?: string | null;
    };
    class?: {
      id?: string | null;
      name?: string | null;
      description?: string | null;
    };
    inventory_branch?: {
      id?: string | null;
      name?: string | null;
      description?: string | null;
      company_id?: string | null;
      company_name?: string | null;
    };
    msp_branch?: {
      id?: string | null;
      name?: string | null;
      description?: string | null;
      company_id?: string | null;
      company_name?: string | null;
    };
    rsp_branch?: {
      id?: string | null;
      name?: string | null;
      description?: string | null;
      company_id?: string | null;
      company_name?: string | null;
    };
    groups?: Array<{
      id?: string | null;
      name?: string | null;
      company_id?: string | null;
      company_name?: string | null;
    }>;
    tsp_companies?: Array<{
      company_id?: string | null;
      company_name?: string | null;
    }>;
    tracker?: {
      id?: string | null;
      device_serial?: string | null;
      company_id?: string | null;
      vendor_id?: string | null;
      created?: string | null;
      updated?: string | null;
      tracker_type_id?: string | null;
    };
    keypad?: Array<string | null>;
  };

  ESDB_ASSET_MODEL: {
    asset_id: string | null;

    model?: {
      id?: string | null;
      name?: string | null;
    };
  };

  ESDB_ASSET_MSP_BRANCH: {
    asset_id: string | null;

    branch?: {
      id?: string | null;
      name?: string | null;
      description?: string | null;
      company_id?: string | null;
      company_name?: string | null;
    };
  };

  ESDB_ASSET_PHOTOS: {
    asset_id: string | null;

    photo_id?: string | null;
    filename?: string | null;
  };

  ESDB_ASSET_RSP_BRANCH: {
    asset_id: string | null;

    branch?: {
      id?: string | null;
      name?: string | null;
      description?: string | null;
      company_id?: string | null;
      company_name?: string | null;
    };
  };

  ESDB_ASSET_TRACKER: {
    asset_id: string | null;

    tracker?: {
      id?: string | null;
      device_serial?: string | null;
      company_id?: string | null;
      vendor_id?: string | null;
      created?: string | null;
      updated?: string | null;
      tracker_type_id?: string | null;
    };
  };

  ESDB_ASSET_TSP_COMPANIES: {
    asset_id: string | null;

    tsp_companies?: Array<{
      company_id?: string | null;
      company_name?: string | null;
    }>;
  };

  ESDB_ASSET_TYPE: {
    asset_id: string | null;

    type?: {
      id?: string | null;
      name?: string | null;
    };
  };

  ESDB_BRANCH: {
    market_id: string | null;

    branch?: {
      id?: string | null;
      name?: string | null;
      description?: string | null;
      company_id?: string | null;
      company_name?: string | null;
    };
  };

  ESDB_GROUPX: {
    group_id: string | null;

    group?: {
      id?: string | null;
      name?: string | null;
      company_id?: string | null;
      company_name?: string | null;
    };
  };

  ESDB_ORDER_ENRICHED: {
    order_id: string | null;

    order_status_id?: string | null;
    order_status_name?: string | null;
    company_id?: string | null;
    company_name?: string | null;
    user_id?: string | null;
    user_first_name?: string | null;
    user_last_name?: string | null;
    user_email?: string | null;
    date_created?: string | null;
    date_updated?: string | null;
  };

  ESDB_ORDER_MATERIALIZED_VIEW: {
    order_id: string | null;

    details?: {
      order_id?: string | null;
      order_status_id?: string | null;
      order_status_name?: string | null;
      company_id?: string | null;
      company_name?: string | null;
      user_id?: string | null;
      user_first_name?: string | null;
      user_last_name?: string | null;
      user_email?: string | null;
      date_created?: string | null;
      date_updated?: string | null;
    };
    rentals?: Array<{
      rental_id?: string | null;
      borrower_user_id?: string | null;
      rental_status_id?: string | null;
      start_date?: string | null;
      end_date?: string | null;
      price?: string | null;
      order_id?: string | null;
      asset_id?: string | null;
      asset_name?: string | null;
      asset_description?: string | null;
      asset_company_id?: string | null;
      asset_company_name?: string | null;
      status_id?: string | null;
      status_name?: string | null;
    }>;
  };

  ESDB_ORDER_WITH_COMPANY: {
    order_id: string | null;

    order_status_id?: string | null;
    order_status_name?: string | null;
    company_id?: string | null;
    company_name?: string | null;
    user_id?: string | null;
    date_created?: string | null;
    date_updated?: string | null;
  };

  ESDB_ORDER_WITH_RENTALS: {
    order_id: string | null;

    rentals?: Array<{
      rental_id?: string | null;
      borrower_user_id?: string | null;
      rental_status_id?: string | null;
      start_date?: string | null;
      end_date?: string | null;
      price?: string | null;
      order_id?: string | null;
      asset_id?: string | null;
      asset_name?: string | null;
      asset_description?: string | null;
      asset_company_id?: string | null;
      asset_company_name?: string | null;
      status_id?: string | null;
      status_name?: string | null;
    }>;
  };

  ESDB_ORDER_WITH_STATUS: {
    order_id: string | null;

    order_status_id?: string | null;
    order_status_name?: string | null;
    company_id?: string | null;
    user_id?: string | null;
    date_created?: string | null;
    date_updated?: string | null;
  };

  ESDB_PUBLIC_ASSET_TYPES: {
    asset_type_id: string | null;

    name?: string | null;
  };

  ESDB_PUBLIC_ASSETS: {
    asset_id: string | null;

    asset_type_id?: string | null;
    name?: string | null;
    description?: string | null;
    custom_name?: string | null;
    model?: string | null;
    year?: string | null;
    company_id?: string | null;
    tracker_id?: string | null;
    vin?: string | null;
    driver_name?: string | null;
    serial_number?: string | null;
    equipment_make_id?: string | null;
    equipment_model_id?: string | null;
    service_branch_id?: string | null;
    inventory_branch_id?: string | null;
    rental_branch_id?: string | null;
    equipment_class_id?: string | null;
    camera_id?: string | null;
    photo_id?: string | null;
  };

  ESDB_PUBLIC_COMPANIES: {
    company_id: string | null;

    name?: string | null;
  };

  ESDB_PUBLIC_EQUIPMENT_CLASSES: {
    equipment_class_id: string | null;

    name?: string | null;
    description?: string | null;
  };

  ESDB_PUBLIC_EQUIPMENT_MAKES: {
    equipment_make_id: string | null;

    name?: string | null;
  };

  ESDB_PUBLIC_EQUIPMENT_MODELS: {
    equipment_model_id: string | null;

    name?: string | null;
  };

  ESDB_PUBLIC_KEYPADS: {
    keypad_id: string | null;

    asset_id?: string | null;
  };

  ESDB_PUBLIC_MARKETS: {
    market_id: string | null;

    name?: string | null;
    description?: string | null;
    company_id?: string | null;
  };

  ESDB_PUBLIC_ORDER_STATUSES: {
    order_status_id: string | null;

    name?: string | null;
  };

  ESDB_PUBLIC_ORDERS: {
    order_id: string | null;

    order_status_id?: string | null;
    company_id?: string | null;
    user_id?: string | null;
    date_created?: string | null;
    date_updated?: string | null;
  };

  ESDB_PUBLIC_ORGANIZATION_ASSET_XREF: {
    organization_asset_xref_id: string | null;

    organization_id?: string | null;
    asset_id?: string | null;
  };

  ESDB_PUBLIC_ORGANIZATIONS: {
    organization_id: string | null;

    name?: string | null;
    company_id?: string | null;
  };

  ESDB_PUBLIC_PHOTOS: {
    photo_id: string | null;

    filename?: string | null;
  };

  ESDB_PUBLIC_RENTAL_STATUSES: {
    rental_status_id: string | null;

    name?: string | null;
  };

  ESDB_PUBLIC_RENTALS: {
    rental_id: string | null;

    borrower_user_id?: string | null;
    rental_status_id?: string | null;
    date_created?: string | null;
    start_date?: string | null;
    end_date?: string | null;
    amount_received?: string | null;
    price?: string | null;
    delivery_charge?: string | null;
    return_charge?: string | null;
    delivery_required?: string | null;
    delivery_instructions?: string | null;
    order_id?: string | null;
    drop_off_delivery_id?: string | null;
    return_delivery_id?: string | null;
    price_per_day?: string | null;
    price_per_week?: string | null;
    price_per_month?: string | null;
    start_date_estimated?: string | null;
    end_date_estimated?: string | null;
    job_description?: string | null;
    equipment_class_id?: string | null;
    price_per_hour?: string | null;
    deleted?: string | null;
    rental_protection_plan_id?: string | null;
    taxable?: string | null;
    asset_id?: string | null;
    drop_off_delivery_required?: string | null;
    return_delivery_required?: string | null;
    lien_notice_sent?: string | null;
    off_rent_date_requested?: string | null;
    external_id?: string | null;
    rental_type_id?: string | null;
    part_type_id?: string | null;
    quantity?: string | null;
    purchase_price?: string | null;
    rental_purchase_option_id?: string | null;
    rate_type_id?: string | null;
    has_re_rent?: string | null;
    is_below_floor_rate?: string | null;
    is_flat_monthly_rate?: string | null;
    is_flexible_rate?: string | null;
    inventory_product_id?: string | null;
    inventory_product_name?: string | null;
    inventory_product_name_historical?: string | null;
    one_time_charge?: string | null;
    rental_pricing_structure_id?: string | null;
  };

  ESDB_PUBLIC_TELEMATICS_SERVICE_PROVIDERS_ASSETS: {
    telematics_service_providers_asset_id: string | null;

    asset_id?: string | null;
    company_id?: string | null;
  };

  ESDB_PUBLIC_TRACKERS: {
    tracker_id: string | null;

    device_serial?: string | null;
    company_id?: string | null;
    vendor_id?: string | null;
    created?: string | null;
    updated?: string | null;
    tracker_type_id?: string | null;
  };

  ESDB_PUBLIC_USERS: {
    user_id: string | null;

    first_name?: string | null;
    last_name?: string | null;
    email_address?: string | null;
    username?: string | null;
  };

  ESDB_RENTAL_ASSET: {
    rental_id: string | null;

    asset?: {
      asset_id?: string | null;
      details?: {
        asset_id?: string | null;
        name?: string | null;
        description?: string | null;
        custom_name?: string | null;
        model?: string | null;
        year?: string | null;
        tracker_id?: string | null;
        vin?: string | null;
        serial_number?: string | null;
        driver_name?: string | null;
        camera_id?: string | null;
        photo_id?: string | null;
      };
      photo?: {
        photo_id?: string | null;
        filename?: string | null;
      };
      company?: {
        id?: string | null;
        name?: string | null;
      };
      type?: {
        id?: string | null;
        name?: string | null;
      };
      make?: {
        id?: string | null;
        name?: string | null;
      };
      model?: {
        id?: string | null;
        name?: string | null;
      };
      class?: {
        id?: string | null;
        name?: string | null;
        description?: string | null;
      };
      inventory_branch?: {
        id?: string | null;
        name?: string | null;
        description?: string | null;
        company_id?: string | null;
        company_name?: string | null;
      };
      msp_branch?: {
        id?: string | null;
        name?: string | null;
        description?: string | null;
        company_id?: string | null;
        company_name?: string | null;
      };
      rsp_branch?: {
        id?: string | null;
        name?: string | null;
        description?: string | null;
        company_id?: string | null;
        company_name?: string | null;
      };
      groups?: Array<{
        id?: string | null;
        name?: string | null;
        company_id?: string | null;
        company_name?: string | null;
      }>;
      tsp_companies?: Array<{
        company_id?: string | null;
        company_name?: string | null;
      }>;
      tracker?: {
        id?: string | null;
        device_serial?: string | null;
        company_id?: string | null;
        vendor_id?: string | null;
        created?: string | null;
        updated?: string | null;
        tracker_type_id?: string | null;
      };
      keypad?: Array<string | null>;
    };
  };

  ESDB_RENTAL_MATERIALIZED_VIEW: {
    rental_id: string | null;

    details?: {
      rental_id?: string | null;
      borrower_user_id?: string | null;
      rental_status_id?: string | null;
      date_created?: string | null;
      start_date?: string | null;
      end_date?: string | null;
      amount_received?: string | null;
      price?: string | null;
      delivery_charge?: string | null;
      return_charge?: string | null;
      delivery_required?: string | null;
      delivery_instructions?: string | null;
      order_id?: string | null;
      drop_off_delivery_id?: string | null;
      return_delivery_id?: string | null;
      price_per_day?: string | null;
      price_per_week?: string | null;
      price_per_month?: string | null;
      start_date_estimated?: string | null;
      end_date_estimated?: string | null;
      job_description?: string | null;
      equipment_class_id?: string | null;
      price_per_hour?: string | null;
      deleted?: string | null;
      rental_protection_plan_id?: string | null;
      taxable?: string | null;
      asset_id?: string | null;
      drop_off_delivery_required?: string | null;
      return_delivery_required?: string | null;
      lien_notice_sent?: string | null;
      off_rent_date_requested?: string | null;
      external_id?: string | null;
      rental_type_id?: string | null;
      part_type_id?: string | null;
      quantity?: string | null;
      purchase_price?: string | null;
      rental_purchase_option_id?: string | null;
      rate_type_id?: string | null;
      has_re_rent?: string | null;
      is_below_floor_rate?: string | null;
      is_flat_monthly_rate?: string | null;
      is_flexible_rate?: string | null;
      inventory_product_id?: string | null;
      inventory_product_name?: string | null;
      inventory_product_name_historical?: string | null;
      one_time_charge?: string | null;
      rental_pricing_structure_id?: string | null;
    };
    asset?: {
      asset_id?: string | null;
      details?: {
        asset_id?: string | null;
        name?: string | null;
        description?: string | null;
        custom_name?: string | null;
        model?: string | null;
        year?: string | null;
        tracker_id?: string | null;
        vin?: string | null;
        serial_number?: string | null;
        driver_name?: string | null;
        camera_id?: string | null;
        photo_id?: string | null;
      };
      photo?: {
        photo_id?: string | null;
        filename?: string | null;
      };
      company?: {
        id?: string | null;
        name?: string | null;
      };
      type?: {
        id?: string | null;
        name?: string | null;
      };
      make?: {
        id?: string | null;
        name?: string | null;
      };
      model?: {
        id?: string | null;
        name?: string | null;
      };
      class?: {
        id?: string | null;
        name?: string | null;
        description?: string | null;
      };
      inventory_branch?: {
        id?: string | null;
        name?: string | null;
        description?: string | null;
        company_id?: string | null;
        company_name?: string | null;
      };
      msp_branch?: {
        id?: string | null;
        name?: string | null;
        description?: string | null;
        company_id?: string | null;
        company_name?: string | null;
      };
      rsp_branch?: {
        id?: string | null;
        name?: string | null;
        description?: string | null;
        company_id?: string | null;
        company_name?: string | null;
      };
      groups?: Array<{
        id?: string | null;
        name?: string | null;
        company_id?: string | null;
        company_name?: string | null;
      }>;
      tsp_companies?: Array<{
        company_id?: string | null;
        company_name?: string | null;
      }>;
      tracker?: {
        id?: string | null;
        device_serial?: string | null;
        company_id?: string | null;
        vendor_id?: string | null;
        created?: string | null;
        updated?: string | null;
        tracker_type_id?: string | null;
      };
      keypad?: Array<string | null>;
    };
    status?: {
      id?: string | null;
      name?: string | null;
    };
    order?: {
      order_id?: string | null;
      order_status_id?: string | null;
      order_status_name?: string | null;
      company_id?: string | null;
      company_name?: string | null;
      ordered_by_user_id?: string | null;
      ordered_by_first_name?: string | null;
      ordered_by_last_name?: string | null;
      ordered_by_email?: string | null;
      date_created?: string | null;
      date_updated?: string | null;
    };
  };

  ESDB_RENTAL_ORDER: {
    rental_id: string | null;

    order?: {
      order_id?: string | null;
      order_status_id?: string | null;
      order_status_name?: string | null;
      company_id?: string | null;
      company_name?: string | null;
      ordered_by_user_id?: string | null;
      ordered_by_first_name?: string | null;
      ordered_by_last_name?: string | null;
      ordered_by_email?: string | null;
      date_created?: string | null;
      date_updated?: string | null;
    };
  };

  ESDB_RENTAL_STATUS: {
    rental_id: string | null;

    status?: {
      id?: string | null;
      name?: string | null;
    };
  };

  PIM_CATEGORIES_MATERIALIZED_VIEW_V1: {
    id: string | null;

    source?: string | null;
    specversion?: string | null;
    type?: string | null;
    time?: string | null;
    data?: {
      name?: string | null;
      path?: string | null;
      description?: string | null;
      has_products?: boolean | null;
      platform_id?: string | null;
      tenant?: {
        id?: string | null;
      };
      created_by?: string | null;
      createdAt?: number | null;
      updatedAt?: number | null;
      is_deleted?: boolean | null;
    };
    category_lvl1?: string | null;
    category_lvl2?: string | null;
    category_lvl3?: string | null;
    category_lvl4?: string | null;
    category_lvl5?: string | null;
    category_lvl6?: string | null;
    category_lvl7?: string | null;
    category_lvl8?: string | null;
    category_lvl9?: string | null;
    category_lvl10?: string | null;
    category_lvl11?: string | null;
    category_lvl12?: string | null;
  };

  PIM_CATEGORIES_REPARTITIONED: {
    id: string | null;

    source?: string | null;
    specversion?: string | null;
    type?: string | null;
    time?: string | null;
    data?: {
      name?: string | null;
      path?: string | null;
      description?: string | null;
      has_products?: boolean | null;
      platform_id?: string | null;
      tenant?: {
        id?: string | null;
      };
      created_by?: string | null;
      createdAt?: number | null;
      updatedAt?: number | null;
      is_deleted?: boolean | null;
    };
    category_lvl1?: string | null;
    category_lvl2?: string | null;
    category_lvl3?: string | null;
    category_lvl4?: string | null;
    category_lvl5?: string | null;
    category_lvl6?: string | null;
    category_lvl7?: string | null;
    category_lvl8?: string | null;
    category_lvl9?: string | null;
    category_lvl10?: string | null;
    category_lvl11?: string | null;
    category_lvl12?: string | null;
  };

  PIM_CATEGORIES_V1: {
    id: string | null;

    source?: string | null;
    specversion?: string | null;
    type?: string | null;
    time?: string | null;
    data?: {
      name?: string | null;
      path?: string | null;
      description?: string | null;
      has_products?: boolean | null;
      platform_id?: string | null;
      tenant?: {
        id?: string | null;
      };
      created_by?: string | null;
      createdAt?: number | null;
      updatedAt?: number | null;
      is_deleted?: boolean | null;
    };
  };

  PIM_CATEGORIES_WITH_SPLIT_PATH_V1: {
    id: string | null;

    source?: string | null;
    specversion?: string | null;
    type?: string | null;
    time?: string | null;
    data?: {
      name?: string | null;
      path?: string | null;
      description?: string | null;
      has_products?: boolean | null;
      platform_id?: string | null;
      tenant?: {
        id?: string | null;
      };
      created_by?: string | null;
      createdAt?: number | null;
      updatedAt?: number | null;
      is_deleted?: boolean | null;
    };
    path_parts?: Array<string | null>;
  };

  PIM_PRODUCTS_MATERIALIZED_VIEW_V1: {
    id: string | null;

    source?: string | null;
    specversion?: string | null;
    type?: string | null;
    time?: string | null;
    data?: {
      platform_id?: string | null;
      tenant?: {
        id?: string | null;
      };
      product_category?: {
        id?: string | null;
        category_platform_id?: string | null;
        name?: string | null;
        path?: string | null;
      };
      product_core_attributes?: {
        name?: string | null;
        make?: string | null;
        make_platform_id?: string | null;
        model?: string | null;
        year?: string | null;
        variant?: string | null;
      };
      product_source_attributes?: {
        manufacturer_part_number?: string | null;
        sku?: string | null;
        source?: string | null;
        upc?: string | null;
      };
      created_by?: string | null;
      createdAt?: number | null;
      updatedAt?: number | null;
      is_deleted?: boolean | null;
      last_published_date?: string | null;
      product_attribute_groups?: Array<{
        name?: string | null;
        attributes?: Array<{
          name?: string | null;
          value?: string | null;
          description?: string | null;
          unit_of_measure?: {
            type?: string | null;
            name?: string | null;
            abbreviation?: string | null;
            classification?: string | null;
            validator_regex?: string | null;
            validation_message?: string | null;
            normalized_unit_name?: string | null;
            normalized_unit_abbreviation?: string | null;
            normalized_value?: string | null;
            id?: string | null;
          };
        }>;
      }>;
      product_category_core_attributes?: Array<{
        name?: string | null;
        value?: string | null;
        description?: string | null;
        unit_of_measure?: {
          type?: string | null;
          name?: string | null;
          abbreviation?: string | null;
          classification?: string | null;
          validator_regex?: string | null;
          validation_message?: string | null;
          normalized_unit_name?: string | null;
          normalized_unit_abbreviation?: string | null;
          normalized_value?: string | null;
          id?: string | null;
        };
      }>;
      product_shipping_dimensions_attributes?: Array<{
        name?: string | null;
        value?: string | null;
        description?: string | null;
        unit_of_measure?: {
          type?: string | null;
          name?: string | null;
          abbreviation?: string | null;
          classification?: string | null;
          validator_regex?: string | null;
          validation_message?: string | null;
          normalized_unit_name?: string | null;
          normalized_unit_abbreviation?: string | null;
          normalized_value?: string | null;
          id?: string | null;
        };
      }>;
      product_options?: Array<{
        name?: string | null;
        options?: Array<{
          name?: string | null;
          value?: string | null;
          is_choices?: boolean | null;
          choices?: Array<{
            name?: string | null;
            value?: string | null;
            attributes?: Array<{
              name?: string | null;
              value?: string | null;
              description?: string | null;
              unit_of_measure?: {
                type?: string | null;
                name?: string | null;
                abbreviation?: string | null;
                classification?: string | null;
                validator_regex?: string | null;
                validation_message?: string | null;
                normalized_unit_name?: string | null;
                normalized_unit_abbreviation?: string | null;
                normalized_value?: string | null;
                id?: string | null;
              };
            }>;
          }>;
          attributes?: Array<{
            name?: string | null;
            value?: string | null;
            description?: string | null;
            unit_of_measure?: {
              type?: string | null;
              name?: string | null;
              abbreviation?: string | null;
              classification?: string | null;
              validator_regex?: string | null;
              validation_message?: string | null;
              normalized_unit_name?: string | null;
              normalized_unit_abbreviation?: string | null;
              normalized_value?: string | null;
              id?: string | null;
            };
          }>;
        }>;
      }>;
      associations?: Array<{
        platform_id?: string | null;
        type?: string | null;
        name?: string | null;
        make?: string | null;
        make_platform_id?: string | null;
        model?: string | null;
        variant?: string | null;
        manufacturer_part_number?: string | null;
        year?: string | null;
        upc?: string | null;
        sku?: string | null;
      }>;
    };
    category_lvl1?: string | null;
    category_lvl2?: string | null;
    category_lvl3?: string | null;
    category_lvl4?: string | null;
    category_lvl5?: string | null;
    category_lvl6?: string | null;
    category_lvl7?: string | null;
    category_lvl8?: string | null;
    category_lvl9?: string | null;
    category_lvl10?: string | null;
    category_lvl11?: string | null;
    category_lvl12?: string | null;
  };

  PIM_PRODUCTS_REPARTITIONED: {
    id: string | null;

    source?: string | null;
    specversion?: string | null;
    type?: string | null;
    time?: string | null;
    data?: {
      platform_id?: string | null;
      tenant?: {
        id?: string | null;
      };
      product_category?: {
        id?: string | null;
        category_platform_id?: string | null;
        name?: string | null;
        path?: string | null;
      };
      product_core_attributes?: {
        name?: string | null;
        make?: string | null;
        make_platform_id?: string | null;
        model?: string | null;
        year?: string | null;
        variant?: string | null;
      };
      product_source_attributes?: {
        manufacturer_part_number?: string | null;
        sku?: string | null;
        source?: string | null;
        upc?: string | null;
      };
      created_by?: string | null;
      createdAt?: number | null;
      updatedAt?: number | null;
      is_deleted?: boolean | null;
      last_published_date?: string | null;
      product_attribute_groups?: Array<{
        name?: string | null;
        attributes?: Array<{
          name?: string | null;
          value?: string | null;
          description?: string | null;
          unit_of_measure?: {
            type?: string | null;
            name?: string | null;
            abbreviation?: string | null;
            classification?: string | null;
            validator_regex?: string | null;
            validation_message?: string | null;
            normalized_unit_name?: string | null;
            normalized_unit_abbreviation?: string | null;
            normalized_value?: string | null;
            id?: string | null;
          };
        }>;
      }>;
      product_category_core_attributes?: Array<{
        name?: string | null;
        value?: string | null;
        description?: string | null;
        unit_of_measure?: {
          type?: string | null;
          name?: string | null;
          abbreviation?: string | null;
          classification?: string | null;
          validator_regex?: string | null;
          validation_message?: string | null;
          normalized_unit_name?: string | null;
          normalized_unit_abbreviation?: string | null;
          normalized_value?: string | null;
          id?: string | null;
        };
      }>;
      product_shipping_dimensions_attributes?: Array<{
        name?: string | null;
        value?: string | null;
        description?: string | null;
        unit_of_measure?: {
          type?: string | null;
          name?: string | null;
          abbreviation?: string | null;
          classification?: string | null;
          validator_regex?: string | null;
          validation_message?: string | null;
          normalized_unit_name?: string | null;
          normalized_unit_abbreviation?: string | null;
          normalized_value?: string | null;
          id?: string | null;
        };
      }>;
      product_options?: Array<{
        name?: string | null;
        options?: Array<{
          name?: string | null;
          value?: string | null;
          is_choices?: boolean | null;
          choices?: Array<{
            name?: string | null;
            value?: string | null;
            attributes?: Array<{
              name?: string | null;
              value?: string | null;
              description?: string | null;
              unit_of_measure?: {
                type?: string | null;
                name?: string | null;
                abbreviation?: string | null;
                classification?: string | null;
                validator_regex?: string | null;
                validation_message?: string | null;
                normalized_unit_name?: string | null;
                normalized_unit_abbreviation?: string | null;
                normalized_value?: string | null;
                id?: string | null;
              };
            }>;
          }>;
          attributes?: Array<{
            name?: string | null;
            value?: string | null;
            description?: string | null;
            unit_of_measure?: {
              type?: string | null;
              name?: string | null;
              abbreviation?: string | null;
              classification?: string | null;
              validator_regex?: string | null;
              validation_message?: string | null;
              normalized_unit_name?: string | null;
              normalized_unit_abbreviation?: string | null;
              normalized_value?: string | null;
              id?: string | null;
            };
          }>;
        }>;
      }>;
      associations?: Array<{
        platform_id?: string | null;
        type?: string | null;
        name?: string | null;
        make?: string | null;
        make_platform_id?: string | null;
        model?: string | null;
        variant?: string | null;
        manufacturer_part_number?: string | null;
        year?: string | null;
        upc?: string | null;
        sku?: string | null;
      }>;
    };
    category_lvl1?: string | null;
    category_lvl2?: string | null;
    category_lvl3?: string | null;
    category_lvl4?: string | null;
    category_lvl5?: string | null;
    category_lvl6?: string | null;
    category_lvl7?: string | null;
    category_lvl8?: string | null;
    category_lvl9?: string | null;
    category_lvl10?: string | null;
    category_lvl11?: string | null;
    category_lvl12?: string | null;
  };

  PIM_PRODUCTS_V1: {
    id: string | null;

    source?: string | null;
    specversion?: string | null;
    type?: string | null;
    time?: string | null;
    data?: {
      platform_id?: string | null;
      tenant?: {
        id?: string | null;
      };
      product_category?: {
        id?: string | null;
        category_platform_id?: string | null;
        name?: string | null;
        path?: string | null;
      };
      product_core_attributes?: {
        name?: string | null;
        make?: string | null;
        make_platform_id?: string | null;
        model?: string | null;
        year?: string | null;
        variant?: string | null;
      };
      product_source_attributes?: {
        manufacturer_part_number?: string | null;
        sku?: string | null;
        source?: string | null;
        upc?: string | null;
      };
      created_by?: string | null;
      createdAt?: number | null;
      updatedAt?: number | null;
      is_deleted?: boolean | null;
      last_published_date?: string | null;
      product_attribute_groups?: Array<{
        name?: string | null;
        attributes?: Array<{
          name?: string | null;
          value?: string | null;
          description?: string | null;
          unit_of_measure?: {
            type?: string | null;
            name?: string | null;
            abbreviation?: string | null;
            classification?: string | null;
            validator_regex?: string | null;
            validation_message?: string | null;
            normalized_unit_name?: string | null;
            normalized_unit_abbreviation?: string | null;
            normalized_value?: string | null;
            id?: string | null;
          };
        }>;
      }>;
      product_category_core_attributes?: Array<{
        name?: string | null;
        value?: string | null;
        description?: string | null;
        unit_of_measure?: {
          type?: string | null;
          name?: string | null;
          abbreviation?: string | null;
          classification?: string | null;
          validator_regex?: string | null;
          validation_message?: string | null;
          normalized_unit_name?: string | null;
          normalized_unit_abbreviation?: string | null;
          normalized_value?: string | null;
          id?: string | null;
        };
      }>;
      product_shipping_dimensions_attributes?: Array<{
        name?: string | null;
        value?: string | null;
        description?: string | null;
        unit_of_measure?: {
          type?: string | null;
          name?: string | null;
          abbreviation?: string | null;
          classification?: string | null;
          validator_regex?: string | null;
          validation_message?: string | null;
          normalized_unit_name?: string | null;
          normalized_unit_abbreviation?: string | null;
          normalized_value?: string | null;
          id?: string | null;
        };
      }>;
      product_options?: Array<{
        name?: string | null;
        options?: Array<{
          name?: string | null;
          value?: string | null;
          is_choices?: boolean | null;
          choices?: Array<{
            name?: string | null;
            value?: string | null;
            attributes?: Array<{
              name?: string | null;
              value?: string | null;
              description?: string | null;
              unit_of_measure?: {
                type?: string | null;
                name?: string | null;
                abbreviation?: string | null;
                classification?: string | null;
                validator_regex?: string | null;
                validation_message?: string | null;
                normalized_unit_name?: string | null;
                normalized_unit_abbreviation?: string | null;
                normalized_value?: string | null;
                id?: string | null;
              };
            }>;
          }>;
          attributes?: Array<{
            name?: string | null;
            value?: string | null;
            description?: string | null;
            unit_of_measure?: {
              type?: string | null;
              name?: string | null;
              abbreviation?: string | null;
              classification?: string | null;
              validator_regex?: string | null;
              validation_message?: string | null;
              normalized_unit_name?: string | null;
              normalized_unit_abbreviation?: string | null;
              normalized_value?: string | null;
              id?: string | null;
            };
          }>;
        }>;
      }>;
      associations?: Array<{
        platform_id?: string | null;
        type?: string | null;
        name?: string | null;
        make?: string | null;
        make_platform_id?: string | null;
        model?: string | null;
        variant?: string | null;
        manufacturer_part_number?: string | null;
        year?: string | null;
        upc?: string | null;
        sku?: string | null;
      }>;
    };
  };

  PIM_PRODUCTS_WITH_SPLIT_CAT_PATH_V1: {
    id: string | null;

    source?: string | null;
    specversion?: string | null;
    type?: string | null;
    time?: string | null;
    data?: {
      platform_id?: string | null;
      tenant?: {
        id?: string | null;
      };
      product_category?: {
        id?: string | null;
        category_platform_id?: string | null;
        name?: string | null;
        path?: string | null;
      };
      product_core_attributes?: {
        name?: string | null;
        make?: string | null;
        make_platform_id?: string | null;
        model?: string | null;
        year?: string | null;
        variant?: string | null;
      };
      product_source_attributes?: {
        manufacturer_part_number?: string | null;
        sku?: string | null;
        source?: string | null;
        upc?: string | null;
      };
      created_by?: string | null;
      createdAt?: number | null;
      updatedAt?: number | null;
      is_deleted?: boolean | null;
      last_published_date?: string | null;
      product_attribute_groups?: Array<{
        name?: string | null;
        attributes?: Array<{
          name?: string | null;
          value?: string | null;
          description?: string | null;
          unit_of_measure?: {
            type?: string | null;
            name?: string | null;
            abbreviation?: string | null;
            classification?: string | null;
            validator_regex?: string | null;
            validation_message?: string | null;
            normalized_unit_name?: string | null;
            normalized_unit_abbreviation?: string | null;
            normalized_value?: string | null;
            id?: string | null;
          };
        }>;
      }>;
      product_category_core_attributes?: Array<{
        name?: string | null;
        value?: string | null;
        description?: string | null;
        unit_of_measure?: {
          type?: string | null;
          name?: string | null;
          abbreviation?: string | null;
          classification?: string | null;
          validator_regex?: string | null;
          validation_message?: string | null;
          normalized_unit_name?: string | null;
          normalized_unit_abbreviation?: string | null;
          normalized_value?: string | null;
          id?: string | null;
        };
      }>;
      product_shipping_dimensions_attributes?: Array<{
        name?: string | null;
        value?: string | null;
        description?: string | null;
        unit_of_measure?: {
          type?: string | null;
          name?: string | null;
          abbreviation?: string | null;
          classification?: string | null;
          validator_regex?: string | null;
          validation_message?: string | null;
          normalized_unit_name?: string | null;
          normalized_unit_abbreviation?: string | null;
          normalized_value?: string | null;
          id?: string | null;
        };
      }>;
      product_options?: Array<{
        name?: string | null;
        options?: Array<{
          name?: string | null;
          value?: string | null;
          is_choices?: boolean | null;
          choices?: Array<{
            name?: string | null;
            value?: string | null;
            attributes?: Array<{
              name?: string | null;
              value?: string | null;
              description?: string | null;
              unit_of_measure?: {
                type?: string | null;
                name?: string | null;
                abbreviation?: string | null;
                classification?: string | null;
                validator_regex?: string | null;
                validation_message?: string | null;
                normalized_unit_name?: string | null;
                normalized_unit_abbreviation?: string | null;
                normalized_value?: string | null;
                id?: string | null;
              };
            }>;
          }>;
          attributes?: Array<{
            name?: string | null;
            value?: string | null;
            description?: string | null;
            unit_of_measure?: {
              type?: string | null;
              name?: string | null;
              abbreviation?: string | null;
              classification?: string | null;
              validator_regex?: string | null;
              validation_message?: string | null;
              normalized_unit_name?: string | null;
              normalized_unit_abbreviation?: string | null;
              normalized_value?: string | null;
              id?: string | null;
            };
          }>;
        }>;
      }>;
      associations?: Array<{
        platform_id?: string | null;
        type?: string | null;
        name?: string | null;
        make?: string | null;
        make_platform_id?: string | null;
        model?: string | null;
        variant?: string | null;
        manufacturer_part_number?: string | null;
        year?: string | null;
        upc?: string | null;
        sku?: string | null;
      }>;
    };
    path_parts?: Array<string | null>;
  };

  PRICE_BOOKS_TABLE: {
    _id: string | null;

    workspaceId?: string | null;
    parentPriceBookId?: string | null;
    parentPriceBookPercentageFactor?: string | null;
    name?: string | null;
    notes?: string | null;
    createdBy?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    updatedBy?: string | null;
    businessContactId?: string | null;
    projectId?: string | null;
    location?: string | null;
    deleted?: boolean | null;
  };

  PRICES_TABLE: {
    _id: string | null;

    workspaceId?: string | null;
    parentPriceId?: string | null;
    parentPriceIdPercentageFactor?: string | null;
    name?: string | null;
    createdBy?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    updatedBy?: string | null;
    pimCategoryId?: string | null;
    pimCategoryPath?: string | null;
    pimCategoryName?: string | null;
    pimProductId?: string | null;
    priceType?: string | null;
    priceBookId?: string | null;
    businessContactId?: string | null;
    projectId?: string | null;
    location?: string | null;
    pricePerDayInCents?: number | null;
    pricePerWeekInCents?: number | null;
    pricePerMonthInCents?: number | null;
    unitCostInCents?: number | null;
    discounts?: string | null;
    deleted?: boolean | null;
  };

  PRICES_WITH_CATEGORY: {
    _id: string | null;

    workspaceId?: string | null;
    parentPriceId?: string | null;
    parentPriceIdPercentageFactor?: string | null;
    name?: string | null;
    createdBy?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    updatedBy?: string | null;
    pimCategoryId?: string | null;
    pimCategoryPath?: string | null;
    pimCategoryName?: string | null;
    pimProductId?: string | null;
    priceType?: string | null;
    priceBookId?: string | null;
    businessContactId?: string | null;
    projectId?: string | null;
    location?: string | null;
    pricePerDayInCents?: number | null;
    pricePerWeekInCents?: number | null;
    pricePerMonthInCents?: number | null;
    unitCostInCents?: number | null;
    discounts?: string | null;
    price_book?: {
      id?: string | null;
      workspace_id?: string | null;
      parent_price_book_id?: string | null;
      parent_price_book_percentage_factor?: string | null;
      name?: string | null;
      notes?: string | null;
      created_by?: string | null;
      created_at?: string | null;
      updated_at?: string | null;
      updated_by?: string | null;
      business_contact_id?: string | null;
      project_id?: string | null;
      location?: string | null;
    };
    pim_category?: {
      id?: string | null;
      source?: string | null;
      specversion?: string | null;
      type?: string | null;
      time?: string | null;
      data?: {
        name?: string | null;
        path?: string | null;
        description?: string | null;
        has_products?: boolean | null;
        platform_id?: string | null;
        tenant?: {
          id?: string | null;
        };
        created_by?: string | null;
        createdAt?: number | null;
        updatedAt?: number | null;
        is_deleted?: boolean | null;
      };
      category_lvl1?: string | null;
      category_lvl2?: string | null;
      category_lvl3?: string | null;
      category_lvl4?: string | null;
      category_lvl5?: string | null;
      category_lvl6?: string | null;
      category_lvl7?: string | null;
      category_lvl8?: string | null;
      category_lvl9?: string | null;
      category_lvl10?: string | null;
      category_lvl11?: string | null;
      category_lvl12?: string | null;
    };
  };

  PRICES_WITH_PRICE_BOOK: {
    _id: string | null;

    workspaceId?: string | null;
    parentPriceId?: string | null;
    parentPriceIdPercentageFactor?: string | null;
    name?: string | null;
    createdBy?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    updatedBy?: string | null;
    pimCategoryId?: string | null;
    pimCategoryPath?: string | null;
    pimCategoryName?: string | null;
    pimProductId?: string | null;
    priceType?: string | null;
    priceBookId?: string | null;
    businessContactId?: string | null;
    projectId?: string | null;
    location?: string | null;
    pricePerDayInCents?: number | null;
    pricePerWeekInCents?: number | null;
    pricePerMonthInCents?: number | null;
    unitCostInCents?: number | null;
    discounts?: string | null;
    price_book?: {
      id?: string | null;
      workspace_id?: string | null;
      parent_price_book_id?: string | null;
      parent_price_book_percentage_factor?: string | null;
      name?: string | null;
      notes?: string | null;
      created_by?: string | null;
      created_at?: string | null;
      updated_at?: string | null;
      updated_by?: string | null;
      business_contact_id?: string | null;
      project_id?: string | null;
      location?: string | null;
    };
  };
};

const tableKeys = {
  ESDB_ASSET_CLASS: 'asset_id',

  ESDB_ASSET_COMPANY: 'asset_id',

  ESDB_ASSET_GROUPS: 'asset_id',

  ESDB_ASSET_INVENTORY_BRANCH: 'asset_id',

  ESDB_ASSET_KEYPADS: 'asset_id',

  ESDB_ASSET_KEYPADS_TABLE: 'keypad_id',

  ESDB_ASSET_MAKE: 'asset_id',

  ESDB_ASSET_MATERIALIZED_VIEW: 'asset_id',

  ESDB_ASSET_MODEL: 'asset_id',

  ESDB_ASSET_MSP_BRANCH: 'asset_id',

  ESDB_ASSET_PHOTOS: 'asset_id',

  ESDB_ASSET_RSP_BRANCH: 'asset_id',

  ESDB_ASSET_TRACKER: 'asset_id',

  ESDB_ASSET_TSP_COMPANIES: 'asset_id',

  ESDB_ASSET_TYPE: 'asset_id',

  ESDB_BRANCH: 'market_id',

  ESDB_GROUPX: 'group_id',

  ESDB_ORDER_ENRICHED: 'order_id',

  ESDB_ORDER_MATERIALIZED_VIEW: 'order_id',

  ESDB_ORDER_WITH_COMPANY: 'order_id',

  ESDB_ORDER_WITH_RENTALS: 'order_id',

  ESDB_ORDER_WITH_STATUS: 'order_id',

  ESDB_PUBLIC_ASSET_TYPES: 'asset_type_id',

  ESDB_PUBLIC_ASSETS: 'asset_id',

  ESDB_PUBLIC_COMPANIES: 'company_id',

  ESDB_PUBLIC_EQUIPMENT_CLASSES: 'equipment_class_id',

  ESDB_PUBLIC_EQUIPMENT_MAKES: 'equipment_make_id',

  ESDB_PUBLIC_EQUIPMENT_MODELS: 'equipment_model_id',

  ESDB_PUBLIC_KEYPADS: 'keypad_id',

  ESDB_PUBLIC_MARKETS: 'market_id',

  ESDB_PUBLIC_ORDER_STATUSES: 'order_status_id',

  ESDB_PUBLIC_ORDERS: 'order_id',

  ESDB_PUBLIC_ORGANIZATION_ASSET_XREF: 'organization_asset_xref_id',

  ESDB_PUBLIC_ORGANIZATIONS: 'organization_id',

  ESDB_PUBLIC_PHOTOS: 'photo_id',

  ESDB_PUBLIC_RENTAL_STATUSES: 'rental_status_id',

  ESDB_PUBLIC_RENTALS: 'rental_id',

  ESDB_PUBLIC_TELEMATICS_SERVICE_PROVIDERS_ASSETS:
    'telematics_service_providers_asset_id',

  ESDB_PUBLIC_TRACKERS: 'tracker_id',

  ESDB_PUBLIC_USERS: 'user_id',

  ESDB_RENTAL_ASSET: 'rental_id',

  ESDB_RENTAL_MATERIALIZED_VIEW: 'rental_id',

  ESDB_RENTAL_ORDER: 'rental_id',

  ESDB_RENTAL_STATUS: 'rental_id',

  PIM_CATEGORIES_MATERIALIZED_VIEW_V1: 'id',

  PIM_CATEGORIES_REPARTITIONED: 'id',

  PIM_CATEGORIES_V1: 'id',

  PIM_CATEGORIES_WITH_SPLIT_PATH_V1: 'id',

  PIM_PRODUCTS_MATERIALIZED_VIEW_V1: 'id',

  PIM_PRODUCTS_REPARTITIONED: 'id',

  PIM_PRODUCTS_V1: 'id',

  PIM_PRODUCTS_WITH_SPLIT_CAT_PATH_V1: 'id',

  PRICE_BOOKS_TABLE: '_id',

  PRICES_TABLE: '_id',

  PRICES_WITH_CATEGORY: '_id',

  PRICES_WITH_PRICE_BOOK: '_id',
};

// Helper to parse ksqlDB endpoint URL into host and port
function parseKsqlEndpoint(endpoint: string = 'http://localhost:8088'): {
  host: string;
  port: number;
} {
  const url = new URL(endpoint);
  return {
    host: url.hostname,
    port: parseInt(url.port) || 8088,
  };
}

export const table = <T extends keyof TableSchemas>(
  name: T,
): {
  insert: (value: TableSchemas[T]) => Promise<void>;
  get: (id: string | number) => Promise<TableSchemas[T]>;
  getMany: (id: string | number, fields?: string) => Promise<TableSchemas[T][]>;
  tombstone: (id: string | number | object) => Promise<void>;
} => {
  return {
    insert: async (value: TableSchemas[T]) => {
      const { host, port } = parseKsqlEndpoint(process.env.KSQLDB_ENDPOINT);
      const client = new KsqldbClient({ host, port });
      try {
        await client.connect();
        const escapedRow = escapeKeysDeep(value);
        const { error, status } = await client.insertInto(name, escapedRow);
        if (error) {
          console.log('Error in insertInto', status);
          console.error(error);
          throw error;
        }
      } catch (err) {
        throw new Error(`Could not insertInto ${name}`);
      } finally {
        await client.disconnect();
      }
    },
    get: async (id: string | number) => {
      const { host, port } = parseKsqlEndpoint(process.env.KSQLDB_ENDPOINT);
      const client = new KsqldbClient({ host, port });

      let key = tableKeys[name];
      if (isLowerCase(key)) {
        key = `\`${key}\``;
      }
      let wherePredicate;
      if (typeof id === 'string') {
        wherePredicate = `${key} = '${id}'`;
      } else {
        wherePredicate = `${key} = ${id}`;
      }
      const query = `select * from ${name} where ${wherePredicate};`;
      try {
        await client.connect();
        const [data] = await client.query(query).then(({ data, error }) => {
          if (error) throw error;
          return data?.rows as any[];
        });
        return data as TableSchemas[T];
      } finally {
        await client.disconnect();
      }
    },
    getMany: async (id: string | number, fields: string = '*') => {
      const { host, port } = parseKsqlEndpoint(process.env.KSQLDB_ENDPOINT);
      const client = new KsqldbClient({ host, port });

      let key = tableKeys[name];
      if (isLowerCase(key)) {
        key = `\`${key}\``;
      }
      let wherePredicate;
      if (typeof id === 'string') {
        wherePredicate = `${key} = '${id}';`;
      } else {
        wherePredicate = `${key} = ${id};`;
      }
      const query = `select ${fields} from ${name} where ${wherePredicate}`;
      try {
        await client.connect();
        const data = await client.query(query).then(({ data, error }) => {
          if (error) throw error;
          return data?.rows as any[];
        });
        return data as TableSchemas[T][];
      } finally {
        await client.disconnect();
      }
    },
    tombstone: async (id: string | number | object) => {
      // 1. Get topic name and key format from ksqlDB
      const { host, port } = parseKsqlEndpoint(process.env.KSQLDB_ENDPOINT);
      const ksqlClient = new KsqldbClient({ host, port });
      let topic: string;
      let keyFormat: string;

      try {
        await ksqlClient.connect();
        const sourceDesc = await ksqlClient.describeSource(name);
        topic = sourceDesc.topic;
        keyFormat = sourceDesc.keyFormat;
      } finally {
        await ksqlClient.disconnect();
      }

      // 2. Format the key based on KEY_FORMAT
      const { execSync } = require('child_process');
      let key: string;

      if (keyFormat === 'JSON') {
        // For JSON key format, serialize the value as JSON
        // This adds quotes around strings: "value" instead of value
        key = JSON.stringify(typeof id === 'object' ? id : String(id));
      } else {
        // For STRING keys (or other formats), use plain string
        key = String(id);
      }

      // 3. Send tombstone via docker exec + rpk (avoids Docker networking issues)
      // Get Redpanda container ID from global setup
      const redpandaContainer = (global as any).__KSQL_REDPANDA__;
      if (!redpandaContainer) {
        throw new Error('Redpanda container not found in global context');
      }

      const containerId = redpandaContainer.getId();

      // Use rpk with -Z flag to produce tombstone (null value)
      // The -Z flag makes rpk treat empty values as tombstones (null)
      // Escape the key for shell
      const escapedKey = key.replace(/"/g, '\\"');
      execSync(
        `echo "" | docker exec -i ${containerId} rpk topic produce ${topic} --key "${escapedKey}" -Z`,
        { stdio: 'inherit' },
      );
    },
  };
};

export const retry = async (action: () => void) => {
  for (let i = 0; i <= 40; i++) {
    try {
      await action();
      break;
    } catch (err) {
      if (i === 40) {
        throw err;
      }
      await sleep(100);
    }
  }
};
