/* eslint-disable */
// Auto-generated from SpiceDB schema. Do not edit by hand.

import { Redis } from 'ioredis';
import { v1 } from '@authzed/authzed-node';
import {
  BaseResourceWithCaching,
  SubjectRelationsMapType,
  SubjectPermissionsMapType,
} from '../spicedb-base-resource/BaseResource';
type AuthzedClient = v1.ZedClientInterface['promises'];

export enum NAMESPACES {
  ERP = 'erp',
}
export enum RESOURCE_TYPES {
  ERP_CHARGE = `${NAMESPACES.ERP}/charge`,
  ERP_CONTACT = `${NAMESPACES.ERP}/contact`,
  ERP_DOMAIN = `${NAMESPACES.ERP}/domain`,
  ERP_FILE = `${NAMESPACES.ERP}/file`,
  ERP_FULFILMENT = `${NAMESPACES.ERP}/fulfilment`,
  ERP_INTAKE_FORM = `${NAMESPACES.ERP}/intake_form`,
  ERP_INTAKE_FORM_SUBMISSION = `${NAMESPACES.ERP}/intake_form_submission`,
  ERP_INVOICE = `${NAMESPACES.ERP}/invoice`,
  ERP_PLATFORM = `${NAMESPACES.ERP}/platform`,
  ERP_PRICEBOOK = `${NAMESPACES.ERP}/pricebook`,
  ERP_PRICEBOOK_PRICE = `${NAMESPACES.ERP}/pricebook_price`,
  ERP_PROJECT = `${NAMESPACES.ERP}/project`,
  ERP_PURCHASE_ORDER = `${NAMESPACES.ERP}/purchase_order`,
  ERP_QUOTE = `${NAMESPACES.ERP}/quote`,
  ERP_RFQ = `${NAMESPACES.ERP}/rfq`,
  ERP_SALES_ORDER = `${NAMESPACES.ERP}/sales_order`,
  ERP_SERVICE_ACCOUNT = `${NAMESPACES.ERP}/service_account`,
  ERP_USER = `${NAMESPACES.ERP}/user`,
  ERP_WORKSPACE = `${NAMESPACES.ERP}/workspace`,
}

export enum ERP_CHARGE_RELATIONS {
  WORKSPACE = 'workspace',
}

export enum ERP_CHARGE_PERMISSIONS {
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
}

export enum ERP_CHARGE_SUBJECT_RELATIONS {
  WORKSPACE_WORKSPACE = 'WORKSPACE_WORKSPACE',
}

export const ERP_CHARGE_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_CHARGE_RELATIONS,
  ERP_CHARGE_SUBJECT_RELATIONS
> = {
  WORKSPACE_WORKSPACE: {
    relation: ERP_CHARGE_RELATIONS.WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
} as const;

export enum ERP_CHARGE_SUBJECT_PERMISSIONS {
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
}

export const ERP_CHARGE_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_CHARGE_PERMISSIONS,
  ERP_CHARGE_SUBJECT_PERMISSIONS
> = {
  USER_READ: {
    permission: ERP_CHARGE_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE: {
    permission: ERP_CHARGE_PERMISSIONS.UPDATE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_DELETE: {
    permission: ERP_CHARGE_PERMISSIONS.DELETE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpChargeResource = (client: AuthzedClient, redis: Redis) =>
  new BaseResourceWithCaching<
    ERP_CHARGE_RELATIONS,
    ERP_CHARGE_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_CHARGE_SUBJECT_RELATIONS,
    ERP_CHARGE_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_CHARGE,
    ERP_CHARGE_SUBJECT_RELATIONS_MAP,
    ERP_CHARGE_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_CONTACT_RELATIONS {
  WORKSPACE = 'workspace',
}

export enum ERP_CONTACT_PERMISSIONS {
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
}

export enum ERP_CONTACT_SUBJECT_RELATIONS {
  WORKSPACE_WORKSPACE = 'WORKSPACE_WORKSPACE',
}

export const ERP_CONTACT_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_CONTACT_RELATIONS,
  ERP_CONTACT_SUBJECT_RELATIONS
> = {
  WORKSPACE_WORKSPACE: {
    relation: ERP_CONTACT_RELATIONS.WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
} as const;

export enum ERP_CONTACT_SUBJECT_PERMISSIONS {
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
}

export const ERP_CONTACT_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_CONTACT_PERMISSIONS,
  ERP_CONTACT_SUBJECT_PERMISSIONS
> = {
  USER_READ: {
    permission: ERP_CONTACT_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE: {
    permission: ERP_CONTACT_PERMISSIONS.UPDATE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_DELETE: {
    permission: ERP_CONTACT_PERMISSIONS.DELETE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpContactResource = (client: AuthzedClient, redis: Redis) =>
  new BaseResourceWithCaching<
    ERP_CONTACT_RELATIONS,
    ERP_CONTACT_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_CONTACT_SUBJECT_RELATIONS,
    ERP_CONTACT_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_CONTACT,
    ERP_CONTACT_SUBJECT_RELATIONS_MAP,
    ERP_CONTACT_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_DOMAIN_RELATIONS {
  MEMBER = 'member',
}

export enum ERP_DOMAIN_PERMISSIONS {
  IS_MEMBER = 'is_member',
}

export enum ERP_DOMAIN_SUBJECT_RELATIONS {
  USER_MEMBER = 'USER_MEMBER',
}

export const ERP_DOMAIN_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_DOMAIN_RELATIONS,
  ERP_DOMAIN_SUBJECT_RELATIONS
> = {
  USER_MEMBER: {
    relation: ERP_DOMAIN_RELATIONS.MEMBER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
} as const;

export enum ERP_DOMAIN_SUBJECT_PERMISSIONS {
  USER_IS_MEMBER = 'USER_IS_MEMBER',
}

export const ERP_DOMAIN_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_DOMAIN_PERMISSIONS,
  ERP_DOMAIN_SUBJECT_PERMISSIONS
> = {
  USER_IS_MEMBER: {
    permission: ERP_DOMAIN_PERMISSIONS.IS_MEMBER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpDomainResource = (client: AuthzedClient, redis: Redis) =>
  new BaseResourceWithCaching<
    ERP_DOMAIN_RELATIONS,
    ERP_DOMAIN_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_DOMAIN_SUBJECT_RELATIONS,
    ERP_DOMAIN_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_DOMAIN,
    ERP_DOMAIN_SUBJECT_RELATIONS_MAP,
    ERP_DOMAIN_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_FILE_RELATIONS {
  WORKSPACE = 'workspace',
  SALES_ORDER = 'sales_order',
  PURCHASE_ORDER = 'purchase_order',
  INVOICE = 'invoice',
  PRICEBOOK = 'pricebook',
  PROJECT = 'project',
}

export enum ERP_FILE_PERMISSIONS {
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
}

export enum ERP_FILE_SUBJECT_RELATIONS {
  WORKSPACE_WORKSPACE = 'WORKSPACE_WORKSPACE',
  SALES_ORDER_SALES_ORDER = 'SALES_ORDER_SALES_ORDER',
  PURCHASE_ORDER_PURCHASE_ORDER = 'PURCHASE_ORDER_PURCHASE_ORDER',
  INVOICE_INVOICE = 'INVOICE_INVOICE',
  PRICEBOOK_PRICEBOOK = 'PRICEBOOK_PRICEBOOK',
  PROJECT_PROJECT = 'PROJECT_PROJECT',
}

export const ERP_FILE_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_FILE_RELATIONS,
  ERP_FILE_SUBJECT_RELATIONS
> = {
  WORKSPACE_WORKSPACE: {
    relation: ERP_FILE_RELATIONS.WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
  SALES_ORDER_SALES_ORDER: {
    relation: ERP_FILE_RELATIONS.SALES_ORDER,
    subjectType: RESOURCE_TYPES.ERP_SALES_ORDER,
  },
  PURCHASE_ORDER_PURCHASE_ORDER: {
    relation: ERP_FILE_RELATIONS.PURCHASE_ORDER,
    subjectType: RESOURCE_TYPES.ERP_PURCHASE_ORDER,
  },
  INVOICE_INVOICE: {
    relation: ERP_FILE_RELATIONS.INVOICE,
    subjectType: RESOURCE_TYPES.ERP_INVOICE,
  },
  PRICEBOOK_PRICEBOOK: {
    relation: ERP_FILE_RELATIONS.PRICEBOOK,
    subjectType: RESOURCE_TYPES.ERP_PRICEBOOK,
  },
  PROJECT_PROJECT: {
    relation: ERP_FILE_RELATIONS.PROJECT,
    subjectType: RESOURCE_TYPES.ERP_PROJECT,
  },
} as const;

export enum ERP_FILE_SUBJECT_PERMISSIONS {
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
}

export const ERP_FILE_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_FILE_PERMISSIONS,
  ERP_FILE_SUBJECT_PERMISSIONS
> = {
  USER_READ: {
    permission: ERP_FILE_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE: {
    permission: ERP_FILE_PERMISSIONS.UPDATE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_DELETE: {
    permission: ERP_FILE_PERMISSIONS.DELETE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpFileResource = (client: AuthzedClient, redis: Redis) =>
  new BaseResourceWithCaching<
    ERP_FILE_RELATIONS,
    ERP_FILE_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_FILE_SUBJECT_RELATIONS,
    ERP_FILE_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_FILE,
    ERP_FILE_SUBJECT_RELATIONS_MAP,
    ERP_FILE_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_FULFILMENT_RELATIONS {
  WORKSPACE = 'workspace',
  SALES_ORDER = 'sales_order',
}

export enum ERP_FULFILMENT_PERMISSIONS {
  READ = 'read',
  UPDATE = 'update',
  MANAGE_RENTAL_PERIOD = 'manage_rental_period',
  DELETE = 'delete',
}

export enum ERP_FULFILMENT_SUBJECT_RELATIONS {
  WORKSPACE_WORKSPACE = 'WORKSPACE_WORKSPACE',
  SALES_ORDER_SALES_ORDER = 'SALES_ORDER_SALES_ORDER',
}

export const ERP_FULFILMENT_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_FULFILMENT_RELATIONS,
  ERP_FULFILMENT_SUBJECT_RELATIONS
> = {
  WORKSPACE_WORKSPACE: {
    relation: ERP_FULFILMENT_RELATIONS.WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
  SALES_ORDER_SALES_ORDER: {
    relation: ERP_FULFILMENT_RELATIONS.SALES_ORDER,
    subjectType: RESOURCE_TYPES.ERP_SALES_ORDER,
  },
} as const;

export enum ERP_FULFILMENT_SUBJECT_PERMISSIONS {
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_MANAGE_RENTAL_PERIOD = 'USER_MANAGE_RENTAL_PERIOD',
  USER_DELETE = 'USER_DELETE',
}

export const ERP_FULFILMENT_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_FULFILMENT_PERMISSIONS,
  ERP_FULFILMENT_SUBJECT_PERMISSIONS
> = {
  USER_READ: {
    permission: ERP_FULFILMENT_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE: {
    permission: ERP_FULFILMENT_PERMISSIONS.UPDATE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_MANAGE_RENTAL_PERIOD: {
    permission: ERP_FULFILMENT_PERMISSIONS.MANAGE_RENTAL_PERIOD,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_DELETE: {
    permission: ERP_FULFILMENT_PERMISSIONS.DELETE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpFulfilmentResource = (
  client: AuthzedClient,
  redis: Redis,
) =>
  new BaseResourceWithCaching<
    ERP_FULFILMENT_RELATIONS,
    ERP_FULFILMENT_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_FULFILMENT_SUBJECT_RELATIONS,
    ERP_FULFILMENT_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_FULFILMENT,
    ERP_FULFILMENT_SUBJECT_RELATIONS_MAP,
    ERP_FULFILMENT_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_INTAKE_FORM_RELATIONS {
  WORKSPACE = 'workspace',
  INVITED_TO_SUBMIT = 'invited_to_submit',
}

export enum ERP_INTAKE_FORM_PERMISSIONS {
  READ = 'read',
  UPDATE = 'update',
  CREATE_SUBMISSION = 'create_submission',
  READ_SUBMISSIONS = 'read_submissions',
  UPDATE_SUBMISSIONS = 'update_submissions',
}

export enum ERP_INTAKE_FORM_SUBJECT_RELATIONS {
  WORKSPACE_WORKSPACE = 'WORKSPACE_WORKSPACE',
  USER_INVITED_TO_SUBMIT = 'USER_INVITED_TO_SUBMIT',
}

export const ERP_INTAKE_FORM_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_INTAKE_FORM_RELATIONS,
  ERP_INTAKE_FORM_SUBJECT_RELATIONS
> = {
  WORKSPACE_WORKSPACE: {
    relation: ERP_INTAKE_FORM_RELATIONS.WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
  USER_INVITED_TO_SUBMIT: {
    relation: ERP_INTAKE_FORM_RELATIONS.INVITED_TO_SUBMIT,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
} as const;

export enum ERP_INTAKE_FORM_SUBJECT_PERMISSIONS {
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_CREATE_SUBMISSION = 'USER_CREATE_SUBMISSION',
  USER_READ_SUBMISSIONS = 'USER_READ_SUBMISSIONS',
  USER_UPDATE_SUBMISSIONS = 'USER_UPDATE_SUBMISSIONS',
}

export const ERP_INTAKE_FORM_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_INTAKE_FORM_PERMISSIONS,
  ERP_INTAKE_FORM_SUBJECT_PERMISSIONS
> = {
  USER_READ: {
    permission: ERP_INTAKE_FORM_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE: {
    permission: ERP_INTAKE_FORM_PERMISSIONS.UPDATE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CREATE_SUBMISSION: {
    permission: ERP_INTAKE_FORM_PERMISSIONS.CREATE_SUBMISSION,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_READ_SUBMISSIONS: {
    permission: ERP_INTAKE_FORM_PERMISSIONS.READ_SUBMISSIONS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE_SUBMISSIONS: {
    permission: ERP_INTAKE_FORM_PERMISSIONS.UPDATE_SUBMISSIONS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpIntakeFormResource = (
  client: AuthzedClient,
  redis: Redis,
) =>
  new BaseResourceWithCaching<
    ERP_INTAKE_FORM_RELATIONS,
    ERP_INTAKE_FORM_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_INTAKE_FORM_SUBJECT_RELATIONS,
    ERP_INTAKE_FORM_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_INTAKE_FORM,
    ERP_INTAKE_FORM_SUBJECT_RELATIONS_MAP,
    ERP_INTAKE_FORM_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_INTAKE_FORM_SUBMISSION_RELATIONS {
  SUBMITTER = 'submitter',
  INTAKE_FORM = 'intake_form',
  BUYERS_WORKSPACE = 'buyers_workspace',
}

export enum ERP_INTAKE_FORM_SUBMISSION_PERMISSIONS {
  READ = 'read',
  UPDATE = 'update',
}

export enum ERP_INTAKE_FORM_SUBMISSION_SUBJECT_RELATIONS {
  USER_SUBMITTER = 'USER_SUBMITTER',
  INTAKE_FORM_INTAKE_FORM = 'INTAKE_FORM_INTAKE_FORM',
  WORKSPACE_BUYERS_WORKSPACE = 'WORKSPACE_BUYERS_WORKSPACE',
}

export const ERP_INTAKE_FORM_SUBMISSION_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_INTAKE_FORM_SUBMISSION_RELATIONS,
  ERP_INTAKE_FORM_SUBMISSION_SUBJECT_RELATIONS
> = {
  USER_SUBMITTER: {
    relation: ERP_INTAKE_FORM_SUBMISSION_RELATIONS.SUBMITTER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  INTAKE_FORM_INTAKE_FORM: {
    relation: ERP_INTAKE_FORM_SUBMISSION_RELATIONS.INTAKE_FORM,
    subjectType: RESOURCE_TYPES.ERP_INTAKE_FORM,
  },
  WORKSPACE_BUYERS_WORKSPACE: {
    relation: ERP_INTAKE_FORM_SUBMISSION_RELATIONS.BUYERS_WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
} as const;

export enum ERP_INTAKE_FORM_SUBMISSION_SUBJECT_PERMISSIONS {
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
}

export const ERP_INTAKE_FORM_SUBMISSION_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_INTAKE_FORM_SUBMISSION_PERMISSIONS,
  ERP_INTAKE_FORM_SUBMISSION_SUBJECT_PERMISSIONS
> = {
  USER_READ: {
    permission: ERP_INTAKE_FORM_SUBMISSION_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE: {
    permission: ERP_INTAKE_FORM_SUBMISSION_PERMISSIONS.UPDATE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpIntakeFormSubmissionResource = (
  client: AuthzedClient,
  redis: Redis,
) =>
  new BaseResourceWithCaching<
    ERP_INTAKE_FORM_SUBMISSION_RELATIONS,
    ERP_INTAKE_FORM_SUBMISSION_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_INTAKE_FORM_SUBMISSION_SUBJECT_RELATIONS,
    ERP_INTAKE_FORM_SUBMISSION_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_INTAKE_FORM_SUBMISSION,
    ERP_INTAKE_FORM_SUBMISSION_SUBJECT_RELATIONS_MAP,
    ERP_INTAKE_FORM_SUBMISSION_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_INVOICE_RELATIONS {
  WORKSPACE = 'workspace',
}

export enum ERP_INVOICE_PERMISSIONS {
  READ = 'read',
  UPDATE = 'update',
}

export enum ERP_INVOICE_SUBJECT_RELATIONS {
  WORKSPACE_WORKSPACE = 'WORKSPACE_WORKSPACE',
}

export const ERP_INVOICE_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_INVOICE_RELATIONS,
  ERP_INVOICE_SUBJECT_RELATIONS
> = {
  WORKSPACE_WORKSPACE: {
    relation: ERP_INVOICE_RELATIONS.WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
} as const;

export enum ERP_INVOICE_SUBJECT_PERMISSIONS {
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
}

export const ERP_INVOICE_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_INVOICE_PERMISSIONS,
  ERP_INVOICE_SUBJECT_PERMISSIONS
> = {
  USER_READ: {
    permission: ERP_INVOICE_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE: {
    permission: ERP_INVOICE_PERMISSIONS.UPDATE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpInvoiceResource = (client: AuthzedClient, redis: Redis) =>
  new BaseResourceWithCaching<
    ERP_INVOICE_RELATIONS,
    ERP_INVOICE_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_INVOICE_SUBJECT_RELATIONS,
    ERP_INVOICE_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_INVOICE,
    ERP_INVOICE_SUBJECT_RELATIONS_MAP,
    ERP_INVOICE_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_PLATFORM_RELATIONS {
  USER_ADMIN = 'user_admin',
  SERVICE_ACCOUNT_ADMIN = 'service_account_admin',
}

export enum ERP_PLATFORM_PERMISSIONS {
  IS_ADMIN = 'is_admin',
}

export enum ERP_PLATFORM_SUBJECT_RELATIONS {
  USER_USER_ADMIN = 'USER_USER_ADMIN',
  SERVICE_ACCOUNT_SERVICE_ACCOUNT_ADMIN = 'SERVICE_ACCOUNT_SERVICE_ACCOUNT_ADMIN',
}

export const ERP_PLATFORM_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_PLATFORM_RELATIONS,
  ERP_PLATFORM_SUBJECT_RELATIONS
> = {
  USER_USER_ADMIN: {
    relation: ERP_PLATFORM_RELATIONS.USER_ADMIN,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  SERVICE_ACCOUNT_SERVICE_ACCOUNT_ADMIN: {
    relation: ERP_PLATFORM_RELATIONS.SERVICE_ACCOUNT_ADMIN,
    subjectType: RESOURCE_TYPES.ERP_SERVICE_ACCOUNT,
  },
} as const;

export enum ERP_PLATFORM_SUBJECT_PERMISSIONS {
  USER_IS_ADMIN = 'USER_IS_ADMIN',
}

export const ERP_PLATFORM_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_PLATFORM_PERMISSIONS,
  ERP_PLATFORM_SUBJECT_PERMISSIONS
> = {
  USER_IS_ADMIN: {
    permission: ERP_PLATFORM_PERMISSIONS.IS_ADMIN,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpPlatformResource = (
  client: AuthzedClient,
  redis: Redis,
) =>
  new BaseResourceWithCaching<
    ERP_PLATFORM_RELATIONS,
    ERP_PLATFORM_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_PLATFORM_SUBJECT_RELATIONS,
    ERP_PLATFORM_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_PLATFORM,
    ERP_PLATFORM_SUBJECT_RELATIONS_MAP,
    ERP_PLATFORM_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_PRICEBOOK_RELATIONS {
  WORKSPACE = 'workspace',
  INTAKE_FORM = 'intake_form',
}

export enum ERP_PRICEBOOK_PERMISSIONS {
  READ = 'read',
  UPDATE = 'update',
}

export enum ERP_PRICEBOOK_SUBJECT_RELATIONS {
  WORKSPACE_WORKSPACE = 'WORKSPACE_WORKSPACE',
  INTAKE_FORM_INTAKE_FORM = 'INTAKE_FORM_INTAKE_FORM',
}

export const ERP_PRICEBOOK_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_PRICEBOOK_RELATIONS,
  ERP_PRICEBOOK_SUBJECT_RELATIONS
> = {
  WORKSPACE_WORKSPACE: {
    relation: ERP_PRICEBOOK_RELATIONS.WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
  INTAKE_FORM_INTAKE_FORM: {
    relation: ERP_PRICEBOOK_RELATIONS.INTAKE_FORM,
    subjectType: RESOURCE_TYPES.ERP_INTAKE_FORM,
  },
} as const;

export enum ERP_PRICEBOOK_SUBJECT_PERMISSIONS {
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
}

export const ERP_PRICEBOOK_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_PRICEBOOK_PERMISSIONS,
  ERP_PRICEBOOK_SUBJECT_PERMISSIONS
> = {
  USER_READ: {
    permission: ERP_PRICEBOOK_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE: {
    permission: ERP_PRICEBOOK_PERMISSIONS.UPDATE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpPricebookResource = (
  client: AuthzedClient,
  redis: Redis,
) =>
  new BaseResourceWithCaching<
    ERP_PRICEBOOK_RELATIONS,
    ERP_PRICEBOOK_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_PRICEBOOK_SUBJECT_RELATIONS,
    ERP_PRICEBOOK_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_PRICEBOOK,
    ERP_PRICEBOOK_SUBJECT_RELATIONS_MAP,
    ERP_PRICEBOOK_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_PRICEBOOK_PRICE_RELATIONS {
  WORKSPACE = 'workspace',
  PRICEBOOK = 'pricebook',
  QUOTE = 'quote',
}

export enum ERP_PRICEBOOK_PRICE_PERMISSIONS {
  READ = 'read',
  UPDATE = 'update',
}

export enum ERP_PRICEBOOK_PRICE_SUBJECT_RELATIONS {
  WORKSPACE_WORKSPACE = 'WORKSPACE_WORKSPACE',
  PRICEBOOK_PRICEBOOK = 'PRICEBOOK_PRICEBOOK',
  QUOTE_QUOTE = 'QUOTE_QUOTE',
}

export const ERP_PRICEBOOK_PRICE_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_PRICEBOOK_PRICE_RELATIONS,
  ERP_PRICEBOOK_PRICE_SUBJECT_RELATIONS
> = {
  WORKSPACE_WORKSPACE: {
    relation: ERP_PRICEBOOK_PRICE_RELATIONS.WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
  PRICEBOOK_PRICEBOOK: {
    relation: ERP_PRICEBOOK_PRICE_RELATIONS.PRICEBOOK,
    subjectType: RESOURCE_TYPES.ERP_PRICEBOOK,
  },
  QUOTE_QUOTE: {
    relation: ERP_PRICEBOOK_PRICE_RELATIONS.QUOTE,
    subjectType: RESOURCE_TYPES.ERP_QUOTE,
  },
} as const;

export enum ERP_PRICEBOOK_PRICE_SUBJECT_PERMISSIONS {
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
}

export const ERP_PRICEBOOK_PRICE_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_PRICEBOOK_PRICE_PERMISSIONS,
  ERP_PRICEBOOK_PRICE_SUBJECT_PERMISSIONS
> = {
  USER_READ: {
    permission: ERP_PRICEBOOK_PRICE_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE: {
    permission: ERP_PRICEBOOK_PRICE_PERMISSIONS.UPDATE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpPricebookPriceResource = (
  client: AuthzedClient,
  redis: Redis,
) =>
  new BaseResourceWithCaching<
    ERP_PRICEBOOK_PRICE_RELATIONS,
    ERP_PRICEBOOK_PRICE_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_PRICEBOOK_PRICE_SUBJECT_RELATIONS,
    ERP_PRICEBOOK_PRICE_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_PRICEBOOK_PRICE,
    ERP_PRICEBOOK_PRICE_SUBJECT_RELATIONS_MAP,
    ERP_PRICEBOOK_PRICE_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_PROJECT_RELATIONS {
  WORKSPACE = 'workspace',
}

export enum ERP_PROJECT_PERMISSIONS {
  READ = 'read',
  UPDATE = 'update',
}

export enum ERP_PROJECT_SUBJECT_RELATIONS {
  WORKSPACE_WORKSPACE = 'WORKSPACE_WORKSPACE',
}

export const ERP_PROJECT_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_PROJECT_RELATIONS,
  ERP_PROJECT_SUBJECT_RELATIONS
> = {
  WORKSPACE_WORKSPACE: {
    relation: ERP_PROJECT_RELATIONS.WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
} as const;

export enum ERP_PROJECT_SUBJECT_PERMISSIONS {
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
}

export const ERP_PROJECT_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_PROJECT_PERMISSIONS,
  ERP_PROJECT_SUBJECT_PERMISSIONS
> = {
  USER_READ: {
    permission: ERP_PROJECT_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE: {
    permission: ERP_PROJECT_PERMISSIONS.UPDATE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpProjectResource = (client: AuthzedClient, redis: Redis) =>
  new BaseResourceWithCaching<
    ERP_PROJECT_RELATIONS,
    ERP_PROJECT_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_PROJECT_SUBJECT_RELATIONS,
    ERP_PROJECT_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_PROJECT,
    ERP_PROJECT_SUBJECT_RELATIONS_MAP,
    ERP_PROJECT_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_PURCHASE_ORDER_RELATIONS {
  WORKSPACE = 'workspace',
  QUOTE = 'quote',
}

export enum ERP_PURCHASE_ORDER_PERMISSIONS {
  READ = 'read',
  UPDATE = 'update',
}

export enum ERP_PURCHASE_ORDER_SUBJECT_RELATIONS {
  WORKSPACE_WORKSPACE = 'WORKSPACE_WORKSPACE',
  QUOTE_QUOTE = 'QUOTE_QUOTE',
}

export const ERP_PURCHASE_ORDER_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_PURCHASE_ORDER_RELATIONS,
  ERP_PURCHASE_ORDER_SUBJECT_RELATIONS
> = {
  WORKSPACE_WORKSPACE: {
    relation: ERP_PURCHASE_ORDER_RELATIONS.WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
  QUOTE_QUOTE: {
    relation: ERP_PURCHASE_ORDER_RELATIONS.QUOTE,
    subjectType: RESOURCE_TYPES.ERP_QUOTE,
  },
} as const;

export enum ERP_PURCHASE_ORDER_SUBJECT_PERMISSIONS {
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
}

export const ERP_PURCHASE_ORDER_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_PURCHASE_ORDER_PERMISSIONS,
  ERP_PURCHASE_ORDER_SUBJECT_PERMISSIONS
> = {
  USER_READ: {
    permission: ERP_PURCHASE_ORDER_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE: {
    permission: ERP_PURCHASE_ORDER_PERMISSIONS.UPDATE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpPurchaseOrderResource = (
  client: AuthzedClient,
  redis: Redis,
) =>
  new BaseResourceWithCaching<
    ERP_PURCHASE_ORDER_RELATIONS,
    ERP_PURCHASE_ORDER_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_PURCHASE_ORDER_SUBJECT_RELATIONS,
    ERP_PURCHASE_ORDER_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_PURCHASE_ORDER,
    ERP_PURCHASE_ORDER_SUBJECT_RELATIONS_MAP,
    ERP_PURCHASE_ORDER_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_QUOTE_RELATIONS {
  SELLERS_WORKSPACE = 'sellers_workspace',
  BUYERS_WORKSPACE = 'buyers_workspace',
  BUYER = 'buyer',
}

export enum ERP_QUOTE_PERMISSIONS {
  READ = 'read',
  UPDATE = 'update',
  ACCEPT = 'accept',
  REJECT = 'reject',
}

export enum ERP_QUOTE_SUBJECT_RELATIONS {
  WORKSPACE_SELLERS_WORKSPACE = 'WORKSPACE_SELLERS_WORKSPACE',
  WORKSPACE_BUYERS_WORKSPACE = 'WORKSPACE_BUYERS_WORKSPACE',
  USER_BUYER = 'USER_BUYER',
}

export const ERP_QUOTE_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_QUOTE_RELATIONS,
  ERP_QUOTE_SUBJECT_RELATIONS
> = {
  WORKSPACE_SELLERS_WORKSPACE: {
    relation: ERP_QUOTE_RELATIONS.SELLERS_WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
  WORKSPACE_BUYERS_WORKSPACE: {
    relation: ERP_QUOTE_RELATIONS.BUYERS_WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
  USER_BUYER: {
    relation: ERP_QUOTE_RELATIONS.BUYER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
} as const;

export enum ERP_QUOTE_SUBJECT_PERMISSIONS {
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_ACCEPT = 'USER_ACCEPT',
  USER_REJECT = 'USER_REJECT',
}

export const ERP_QUOTE_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_QUOTE_PERMISSIONS,
  ERP_QUOTE_SUBJECT_PERMISSIONS
> = {
  USER_READ: {
    permission: ERP_QUOTE_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE: {
    permission: ERP_QUOTE_PERMISSIONS.UPDATE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_ACCEPT: {
    permission: ERP_QUOTE_PERMISSIONS.ACCEPT,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_REJECT: {
    permission: ERP_QUOTE_PERMISSIONS.REJECT,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpQuoteResource = (client: AuthzedClient, redis: Redis) =>
  new BaseResourceWithCaching<
    ERP_QUOTE_RELATIONS,
    ERP_QUOTE_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_QUOTE_SUBJECT_RELATIONS,
    ERP_QUOTE_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_QUOTE,
    ERP_QUOTE_SUBJECT_RELATIONS_MAP,
    ERP_QUOTE_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_RFQ_RELATIONS {
  BUYERS_WORKSPACE = 'buyers_workspace',
  INVITED_SELLER = 'invited_seller',
}

export enum ERP_RFQ_PERMISSIONS {
  READ = 'read',
  UPDATE = 'update',
}

export enum ERP_RFQ_SUBJECT_RELATIONS {
  WORKSPACE_BUYERS_WORKSPACE = 'WORKSPACE_BUYERS_WORKSPACE',
  USER_INVITED_SELLER = 'USER_INVITED_SELLER',
}

export const ERP_RFQ_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_RFQ_RELATIONS,
  ERP_RFQ_SUBJECT_RELATIONS
> = {
  WORKSPACE_BUYERS_WORKSPACE: {
    relation: ERP_RFQ_RELATIONS.BUYERS_WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
  USER_INVITED_SELLER: {
    relation: ERP_RFQ_RELATIONS.INVITED_SELLER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
} as const;

export enum ERP_RFQ_SUBJECT_PERMISSIONS {
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
}

export const ERP_RFQ_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_RFQ_PERMISSIONS,
  ERP_RFQ_SUBJECT_PERMISSIONS
> = {
  USER_READ: {
    permission: ERP_RFQ_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE: {
    permission: ERP_RFQ_PERMISSIONS.UPDATE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpRfqResource = (client: AuthzedClient, redis: Redis) =>
  new BaseResourceWithCaching<
    ERP_RFQ_RELATIONS,
    ERP_RFQ_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_RFQ_SUBJECT_RELATIONS,
    ERP_RFQ_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_RFQ,
    ERP_RFQ_SUBJECT_RELATIONS_MAP,
    ERP_RFQ_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_SALES_ORDER_RELATIONS {
  WORKSPACE = 'workspace',
  INTAKE_FORM_SUBMISSION = 'intake_form_submission',
  QUOTE = 'quote',
}

export enum ERP_SALES_ORDER_PERMISSIONS {
  READ = 'read',
  UPDATE = 'update',
  PORTAL_ACCESS = 'portal_access',
}

export enum ERP_SALES_ORDER_SUBJECT_RELATIONS {
  WORKSPACE_WORKSPACE = 'WORKSPACE_WORKSPACE',
  INTAKE_FORM_SUBMISSION_INTAKE_FORM_SUBMISSION = 'INTAKE_FORM_SUBMISSION_INTAKE_FORM_SUBMISSION',
  QUOTE_QUOTE = 'QUOTE_QUOTE',
}

export const ERP_SALES_ORDER_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_SALES_ORDER_RELATIONS,
  ERP_SALES_ORDER_SUBJECT_RELATIONS
> = {
  WORKSPACE_WORKSPACE: {
    relation: ERP_SALES_ORDER_RELATIONS.WORKSPACE,
    subjectType: RESOURCE_TYPES.ERP_WORKSPACE,
  },
  INTAKE_FORM_SUBMISSION_INTAKE_FORM_SUBMISSION: {
    relation: ERP_SALES_ORDER_RELATIONS.INTAKE_FORM_SUBMISSION,
    subjectType: RESOURCE_TYPES.ERP_INTAKE_FORM_SUBMISSION,
  },
  QUOTE_QUOTE: {
    relation: ERP_SALES_ORDER_RELATIONS.QUOTE,
    subjectType: RESOURCE_TYPES.ERP_QUOTE,
  },
} as const;

export enum ERP_SALES_ORDER_SUBJECT_PERMISSIONS {
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_PORTAL_ACCESS = 'USER_PORTAL_ACCESS',
}

export const ERP_SALES_ORDER_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_SALES_ORDER_PERMISSIONS,
  ERP_SALES_ORDER_SUBJECT_PERMISSIONS
> = {
  USER_READ: {
    permission: ERP_SALES_ORDER_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE: {
    permission: ERP_SALES_ORDER_PERMISSIONS.UPDATE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_PORTAL_ACCESS: {
    permission: ERP_SALES_ORDER_PERMISSIONS.PORTAL_ACCESS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpSalesOrderResource = (
  client: AuthzedClient,
  redis: Redis,
) =>
  new BaseResourceWithCaching<
    ERP_SALES_ORDER_RELATIONS,
    ERP_SALES_ORDER_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_SALES_ORDER_SUBJECT_RELATIONS,
    ERP_SALES_ORDER_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_SALES_ORDER,
    ERP_SALES_ORDER_SUBJECT_RELATIONS_MAP,
    ERP_SALES_ORDER_SUBJECT_PERMISSIONS_MAP,
  );

export enum ERP_SERVICE_ACCOUNT_RELATIONS {}

export enum ERP_SERVICE_ACCOUNT_PERMISSIONS {}

export enum ERP_SERVICE_ACCOUNT_SUBJECT_RELATIONS {}

export enum ERP_SERVICE_ACCOUNT_SUBJECT_PERMISSIONS {}

// No factory for ERP_SERVICE_ACCOUNT (no relations or permissions).

export enum ERP_USER_RELATIONS {}

export enum ERP_USER_PERMISSIONS {}

export enum ERP_USER_SUBJECT_RELATIONS {}

export enum ERP_USER_SUBJECT_PERMISSIONS {}

// No factory for ERP_USER (no relations or permissions).

export enum ERP_WORKSPACE_RELATIONS {
  PLATFORM = 'platform',
  DOMAIN = 'domain',
  ADMIN = 'admin',
  MEMBER = 'member',
  ALL_RESOURCES_READER = 'all_resources_reader',
  QUOTES_READER = 'quotes_reader',
  QUOTES_MANAGER = 'quotes_manager',
  RFQS_READER = 'rfqs_reader',
  RFQS_MANAGER = 'rfqs_manager',
  SALES_ORDER_READER = 'sales_order_reader',
  SALES_ORDER_MANAGER = 'sales_order_manager',
  PURCHASE_ORDER_READER = 'purchase_order_reader',
  PURCHASE_ORDER_MANAGER = 'purchase_order_manager',
  PRICE_BOOKS_MANAGER = 'price_books_manager',
  PRICE_BOOKS_READER = 'price_books_reader',
  INTAKE_FORMS_MANAGER = 'intake_forms_manager',
  INTAKE_FORMS_READER = 'intake_forms_reader',
  INTAKE_FORM_SUBMISSIONS_MANAGER = 'intake_form_submissions_manager',
  INTAKE_FORM_SUBMISSIONS_READER = 'intake_form_submissions_reader',
  BUYER_INTAKE_FORM_SUBMISSIONS_MANAGER = 'buyer_intake_form_submissions_manager',
  BUYER_INTAKE_FORM_SUBMISSIONS_READER = 'buyer_intake_form_submissions_reader',
  INVOICE_READER = 'invoice_reader',
  INVOICE_MANAGER = 'invoice_manager',
  PROJECT_READER = 'project_reader',
  PROJECT_MANAGER = 'project_manager',
  CONTACT_READER = 'contact_reader',
  CONTACT_MANAGER = 'contact_manager',
  CHARGE_READER = 'charge_reader',
  CHARGE_MANAGER = 'charge_manager',
  FILE_READER = 'file_reader',
  FILE_MANAGER = 'file_manager',
}

export enum ERP_WORKSPACE_PERMISSIONS {
  IS_ADMIN = 'is_admin',
  CAN_JOIN = 'can_join',
  READ = 'read',
  MANAGE = 'manage',
  ADD_USER = 'add_user',
  REMOVE_USER = 'remove_user',
  UPDATE_USER_ROLES = 'update_user_roles',
  CAN_MANAGE_REFERENCE_NUMBER_TEMPLATES = 'can_manage_reference_number_templates',
  CAN_READ_REFERENCE_NUMBER_TEMPLATES = 'can_read_reference_number_templates',
  CAN_MANAGE_QUOTES = 'can_manage_quotes',
  CAN_READ_QUOTES = 'can_read_quotes',
  CAN_MANAGE_RFQS = 'can_manage_rfqs',
  CAN_READ_RFQS = 'can_read_rfqs',
  CAN_MANAGE_SALES_ORDERS = 'can_manage_sales_orders',
  CAN_READ_SALES_ORDERS = 'can_read_sales_orders',
  CAN_MANAGE_PURCHASE_ORDERS = 'can_manage_purchase_orders',
  CAN_READ_PURCHASE_ORDERS = 'can_read_purchase_orders',
  CAN_MANAGE_PRICE_BOOKS = 'can_manage_price_books',
  CAN_MANAGE_PRICES = 'can_manage_prices',
  CREATE_PRICE_BOOK = 'create_price_book',
  READ_PRICE_BOOKS = 'read_price_books',
  READ_PRICES = 'read_prices',
  CAN_MANAGE_INTAKE_FORMS = 'can_manage_intake_forms',
  CREATE_INTAKE_FORM = 'create_intake_form',
  READ_INTAKE_FORMS = 'read_intake_forms',
  CAN_MANAGE_INTAKE_FORM_SUBMISSIONS = 'can_manage_intake_form_submissions',
  CREATE_INTAKE_FORM_SUBMISSION = 'create_intake_form_submission',
  READ_INTAKE_FORM_SUBMISSIONS = 'read_intake_form_submissions',
  CAN_MANAGE_BUYER_INTAKE_FORM_SUBMISSIONS = 'can_manage_buyer_intake_form_submissions',
  CAN_READ_BUYER_INTAKE_FORM_SUBMISSIONS = 'can_read_buyer_intake_form_submissions',
  CAN_MANAGE_INVOICES = 'can_manage_invoices',
  CAN_READ_INVOICES = 'can_read_invoices',
  CAN_MANAGE_PROJECTS = 'can_manage_projects',
  CAN_READ_PROJECTS = 'can_read_projects',
  CAN_MANAGE_CONTACTS = 'can_manage_contacts',
  CAN_READ_CONTACTS = 'can_read_contacts',
  CAN_MANAGE_CHARGES = 'can_manage_charges',
  CAN_READ_CHARGES = 'can_read_charges',
  CAN_MANAGE_FILES = 'can_manage_files',
  CAN_READ_FILES = 'can_read_files',
}

export enum ERP_WORKSPACE_SUBJECT_RELATIONS {
  PLATFORM_PLATFORM = 'PLATFORM_PLATFORM',
  DOMAIN_DOMAIN = 'DOMAIN_DOMAIN',
  USER_ADMIN = 'USER_ADMIN',
  USER_MEMBER = 'USER_MEMBER',
  USER_ALL_RESOURCES_READER = 'USER_ALL_RESOURCES_READER',
  USER_QUOTES_READER = 'USER_QUOTES_READER',
  USER_QUOTES_MANAGER = 'USER_QUOTES_MANAGER',
  USER_RFQS_READER = 'USER_RFQS_READER',
  USER_RFQS_MANAGER = 'USER_RFQS_MANAGER',
  USER_SALES_ORDER_READER = 'USER_SALES_ORDER_READER',
  USER_SALES_ORDER_MANAGER = 'USER_SALES_ORDER_MANAGER',
  USER_PURCHASE_ORDER_READER = 'USER_PURCHASE_ORDER_READER',
  USER_PURCHASE_ORDER_MANAGER = 'USER_PURCHASE_ORDER_MANAGER',
  USER_PRICE_BOOKS_MANAGER = 'USER_PRICE_BOOKS_MANAGER',
  USER_PRICE_BOOKS_READER = 'USER_PRICE_BOOKS_READER',
  USER_INTAKE_FORMS_MANAGER = 'USER_INTAKE_FORMS_MANAGER',
  USER_INTAKE_FORMS_READER = 'USER_INTAKE_FORMS_READER',
  USER_INTAKE_FORM_SUBMISSIONS_MANAGER = 'USER_INTAKE_FORM_SUBMISSIONS_MANAGER',
  USER_INTAKE_FORM_SUBMISSIONS_READER = 'USER_INTAKE_FORM_SUBMISSIONS_READER',
  USER_BUYER_INTAKE_FORM_SUBMISSIONS_MANAGER = 'USER_BUYER_INTAKE_FORM_SUBMISSIONS_MANAGER',
  USER_BUYER_INTAKE_FORM_SUBMISSIONS_READER = 'USER_BUYER_INTAKE_FORM_SUBMISSIONS_READER',
  USER_INVOICE_READER = 'USER_INVOICE_READER',
  USER_INVOICE_MANAGER = 'USER_INVOICE_MANAGER',
  USER_PROJECT_READER = 'USER_PROJECT_READER',
  USER_PROJECT_MANAGER = 'USER_PROJECT_MANAGER',
  USER_CONTACT_READER = 'USER_CONTACT_READER',
  USER_CONTACT_MANAGER = 'USER_CONTACT_MANAGER',
  USER_CHARGE_READER = 'USER_CHARGE_READER',
  USER_CHARGE_MANAGER = 'USER_CHARGE_MANAGER',
  USER_FILE_READER = 'USER_FILE_READER',
  USER_FILE_MANAGER = 'USER_FILE_MANAGER',
}

export const ERP_WORKSPACE_SUBJECT_RELATIONS_MAP: SubjectRelationsMapType<
  RESOURCE_TYPES,
  ERP_WORKSPACE_RELATIONS,
  ERP_WORKSPACE_SUBJECT_RELATIONS
> = {
  PLATFORM_PLATFORM: {
    relation: ERP_WORKSPACE_RELATIONS.PLATFORM,
    subjectType: RESOURCE_TYPES.ERP_PLATFORM,
  },
  DOMAIN_DOMAIN: {
    relation: ERP_WORKSPACE_RELATIONS.DOMAIN,
    subjectType: RESOURCE_TYPES.ERP_DOMAIN,
  },
  USER_ADMIN: {
    relation: ERP_WORKSPACE_RELATIONS.ADMIN,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_MEMBER: {
    relation: ERP_WORKSPACE_RELATIONS.MEMBER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_ALL_RESOURCES_READER: {
    relation: ERP_WORKSPACE_RELATIONS.ALL_RESOURCES_READER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_QUOTES_READER: {
    relation: ERP_WORKSPACE_RELATIONS.QUOTES_READER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_QUOTES_MANAGER: {
    relation: ERP_WORKSPACE_RELATIONS.QUOTES_MANAGER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_RFQS_READER: {
    relation: ERP_WORKSPACE_RELATIONS.RFQS_READER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_RFQS_MANAGER: {
    relation: ERP_WORKSPACE_RELATIONS.RFQS_MANAGER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_SALES_ORDER_READER: {
    relation: ERP_WORKSPACE_RELATIONS.SALES_ORDER_READER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_SALES_ORDER_MANAGER: {
    relation: ERP_WORKSPACE_RELATIONS.SALES_ORDER_MANAGER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_PURCHASE_ORDER_READER: {
    relation: ERP_WORKSPACE_RELATIONS.PURCHASE_ORDER_READER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_PURCHASE_ORDER_MANAGER: {
    relation: ERP_WORKSPACE_RELATIONS.PURCHASE_ORDER_MANAGER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_PRICE_BOOKS_MANAGER: {
    relation: ERP_WORKSPACE_RELATIONS.PRICE_BOOKS_MANAGER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_PRICE_BOOKS_READER: {
    relation: ERP_WORKSPACE_RELATIONS.PRICE_BOOKS_READER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_INTAKE_FORMS_MANAGER: {
    relation: ERP_WORKSPACE_RELATIONS.INTAKE_FORMS_MANAGER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_INTAKE_FORMS_READER: {
    relation: ERP_WORKSPACE_RELATIONS.INTAKE_FORMS_READER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_INTAKE_FORM_SUBMISSIONS_MANAGER: {
    relation: ERP_WORKSPACE_RELATIONS.INTAKE_FORM_SUBMISSIONS_MANAGER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_INTAKE_FORM_SUBMISSIONS_READER: {
    relation: ERP_WORKSPACE_RELATIONS.INTAKE_FORM_SUBMISSIONS_READER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_BUYER_INTAKE_FORM_SUBMISSIONS_MANAGER: {
    relation: ERP_WORKSPACE_RELATIONS.BUYER_INTAKE_FORM_SUBMISSIONS_MANAGER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_BUYER_INTAKE_FORM_SUBMISSIONS_READER: {
    relation: ERP_WORKSPACE_RELATIONS.BUYER_INTAKE_FORM_SUBMISSIONS_READER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_INVOICE_READER: {
    relation: ERP_WORKSPACE_RELATIONS.INVOICE_READER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_INVOICE_MANAGER: {
    relation: ERP_WORKSPACE_RELATIONS.INVOICE_MANAGER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_PROJECT_READER: {
    relation: ERP_WORKSPACE_RELATIONS.PROJECT_READER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_PROJECT_MANAGER: {
    relation: ERP_WORKSPACE_RELATIONS.PROJECT_MANAGER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CONTACT_READER: {
    relation: ERP_WORKSPACE_RELATIONS.CONTACT_READER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CONTACT_MANAGER: {
    relation: ERP_WORKSPACE_RELATIONS.CONTACT_MANAGER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CHARGE_READER: {
    relation: ERP_WORKSPACE_RELATIONS.CHARGE_READER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CHARGE_MANAGER: {
    relation: ERP_WORKSPACE_RELATIONS.CHARGE_MANAGER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_FILE_READER: {
    relation: ERP_WORKSPACE_RELATIONS.FILE_READER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_FILE_MANAGER: {
    relation: ERP_WORKSPACE_RELATIONS.FILE_MANAGER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
} as const;

export enum ERP_WORKSPACE_SUBJECT_PERMISSIONS {
  USER_IS_ADMIN = 'USER_IS_ADMIN',
  USER_CAN_JOIN = 'USER_CAN_JOIN',
  USER_READ = 'USER_READ',
  USER_MANAGE = 'USER_MANAGE',
  USER_ADD_USER = 'USER_ADD_USER',
  USER_REMOVE_USER = 'USER_REMOVE_USER',
  USER_UPDATE_USER_ROLES = 'USER_UPDATE_USER_ROLES',
  USER_CAN_MANAGE_REFERENCE_NUMBER_TEMPLATES = 'USER_CAN_MANAGE_REFERENCE_NUMBER_TEMPLATES',
  USER_CAN_READ_REFERENCE_NUMBER_TEMPLATES = 'USER_CAN_READ_REFERENCE_NUMBER_TEMPLATES',
  USER_CAN_MANAGE_QUOTES = 'USER_CAN_MANAGE_QUOTES',
  USER_CAN_READ_QUOTES = 'USER_CAN_READ_QUOTES',
  USER_CAN_MANAGE_RFQS = 'USER_CAN_MANAGE_RFQS',
  USER_CAN_READ_RFQS = 'USER_CAN_READ_RFQS',
  USER_CAN_MANAGE_SALES_ORDERS = 'USER_CAN_MANAGE_SALES_ORDERS',
  USER_CAN_READ_SALES_ORDERS = 'USER_CAN_READ_SALES_ORDERS',
  USER_CAN_MANAGE_PURCHASE_ORDERS = 'USER_CAN_MANAGE_PURCHASE_ORDERS',
  USER_CAN_READ_PURCHASE_ORDERS = 'USER_CAN_READ_PURCHASE_ORDERS',
  USER_CAN_MANAGE_PRICE_BOOKS = 'USER_CAN_MANAGE_PRICE_BOOKS',
  USER_CAN_MANAGE_PRICES = 'USER_CAN_MANAGE_PRICES',
  USER_CREATE_PRICE_BOOK = 'USER_CREATE_PRICE_BOOK',
  USER_READ_PRICE_BOOKS = 'USER_READ_PRICE_BOOKS',
  USER_READ_PRICES = 'USER_READ_PRICES',
  USER_CAN_MANAGE_INTAKE_FORMS = 'USER_CAN_MANAGE_INTAKE_FORMS',
  USER_CREATE_INTAKE_FORM = 'USER_CREATE_INTAKE_FORM',
  USER_READ_INTAKE_FORMS = 'USER_READ_INTAKE_FORMS',
  USER_CAN_MANAGE_INTAKE_FORM_SUBMISSIONS = 'USER_CAN_MANAGE_INTAKE_FORM_SUBMISSIONS',
  USER_CREATE_INTAKE_FORM_SUBMISSION = 'USER_CREATE_INTAKE_FORM_SUBMISSION',
  USER_READ_INTAKE_FORM_SUBMISSIONS = 'USER_READ_INTAKE_FORM_SUBMISSIONS',
  USER_CAN_MANAGE_BUYER_INTAKE_FORM_SUBMISSIONS = 'USER_CAN_MANAGE_BUYER_INTAKE_FORM_SUBMISSIONS',
  USER_CAN_READ_BUYER_INTAKE_FORM_SUBMISSIONS = 'USER_CAN_READ_BUYER_INTAKE_FORM_SUBMISSIONS',
  USER_CAN_MANAGE_INVOICES = 'USER_CAN_MANAGE_INVOICES',
  USER_CAN_READ_INVOICES = 'USER_CAN_READ_INVOICES',
  USER_CAN_MANAGE_PROJECTS = 'USER_CAN_MANAGE_PROJECTS',
  USER_CAN_READ_PROJECTS = 'USER_CAN_READ_PROJECTS',
  USER_CAN_MANAGE_CONTACTS = 'USER_CAN_MANAGE_CONTACTS',
  USER_CAN_READ_CONTACTS = 'USER_CAN_READ_CONTACTS',
  USER_CAN_MANAGE_CHARGES = 'USER_CAN_MANAGE_CHARGES',
  USER_CAN_READ_CHARGES = 'USER_CAN_READ_CHARGES',
  USER_CAN_MANAGE_FILES = 'USER_CAN_MANAGE_FILES',
  USER_CAN_READ_FILES = 'USER_CAN_READ_FILES',
}

export const ERP_WORKSPACE_SUBJECT_PERMISSIONS_MAP: SubjectPermissionsMapType<
  RESOURCE_TYPES,
  ERP_WORKSPACE_PERMISSIONS,
  ERP_WORKSPACE_SUBJECT_PERMISSIONS
> = {
  USER_IS_ADMIN: {
    permission: ERP_WORKSPACE_PERMISSIONS.IS_ADMIN,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_JOIN: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_JOIN,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_READ: {
    permission: ERP_WORKSPACE_PERMISSIONS.READ,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_MANAGE: {
    permission: ERP_WORKSPACE_PERMISSIONS.MANAGE,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_ADD_USER: {
    permission: ERP_WORKSPACE_PERMISSIONS.ADD_USER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_REMOVE_USER: {
    permission: ERP_WORKSPACE_PERMISSIONS.REMOVE_USER,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_UPDATE_USER_ROLES: {
    permission: ERP_WORKSPACE_PERMISSIONS.UPDATE_USER_ROLES,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_REFERENCE_NUMBER_TEMPLATES: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_REFERENCE_NUMBER_TEMPLATES,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_READ_REFERENCE_NUMBER_TEMPLATES: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_READ_REFERENCE_NUMBER_TEMPLATES,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_QUOTES: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_QUOTES,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_READ_QUOTES: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_READ_QUOTES,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_RFQS: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_RFQS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_READ_RFQS: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_READ_RFQS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_SALES_ORDERS: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_SALES_ORDERS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_READ_SALES_ORDERS: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_READ_SALES_ORDERS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_PURCHASE_ORDERS: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_PURCHASE_ORDERS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_READ_PURCHASE_ORDERS: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_READ_PURCHASE_ORDERS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_PRICE_BOOKS: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_PRICE_BOOKS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_PRICES: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_PRICES,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CREATE_PRICE_BOOK: {
    permission: ERP_WORKSPACE_PERMISSIONS.CREATE_PRICE_BOOK,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_READ_PRICE_BOOKS: {
    permission: ERP_WORKSPACE_PERMISSIONS.READ_PRICE_BOOKS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_READ_PRICES: {
    permission: ERP_WORKSPACE_PERMISSIONS.READ_PRICES,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_INTAKE_FORMS: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_INTAKE_FORMS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CREATE_INTAKE_FORM: {
    permission: ERP_WORKSPACE_PERMISSIONS.CREATE_INTAKE_FORM,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_READ_INTAKE_FORMS: {
    permission: ERP_WORKSPACE_PERMISSIONS.READ_INTAKE_FORMS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_INTAKE_FORM_SUBMISSIONS: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_INTAKE_FORM_SUBMISSIONS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CREATE_INTAKE_FORM_SUBMISSION: {
    permission: ERP_WORKSPACE_PERMISSIONS.CREATE_INTAKE_FORM_SUBMISSION,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_READ_INTAKE_FORM_SUBMISSIONS: {
    permission: ERP_WORKSPACE_PERMISSIONS.READ_INTAKE_FORM_SUBMISSIONS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_BUYER_INTAKE_FORM_SUBMISSIONS: {
    permission:
      ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_BUYER_INTAKE_FORM_SUBMISSIONS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_READ_BUYER_INTAKE_FORM_SUBMISSIONS: {
    permission:
      ERP_WORKSPACE_PERMISSIONS.CAN_READ_BUYER_INTAKE_FORM_SUBMISSIONS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_INVOICES: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_INVOICES,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_READ_INVOICES: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_READ_INVOICES,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_PROJECTS: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_PROJECTS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_READ_PROJECTS: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_READ_PROJECTS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_CONTACTS: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_CONTACTS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_READ_CONTACTS: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_READ_CONTACTS,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_CHARGES: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_CHARGES,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_READ_CHARGES: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_READ_CHARGES,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_MANAGE_FILES: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_MANAGE_FILES,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
  USER_CAN_READ_FILES: {
    permission: ERP_WORKSPACE_PERMISSIONS.CAN_READ_FILES,
    subjectType: RESOURCE_TYPES.ERP_USER,
  },
};

export const createErpWorkspaceResource = (
  client: AuthzedClient,
  redis: Redis,
) =>
  new BaseResourceWithCaching<
    ERP_WORKSPACE_RELATIONS,
    ERP_WORKSPACE_PERMISSIONS,
    RESOURCE_TYPES,
    ERP_WORKSPACE_SUBJECT_RELATIONS,
    ERP_WORKSPACE_SUBJECT_PERMISSIONS
  >(
    client,
    redis,
    RESOURCE_TYPES.ERP_WORKSPACE,
    ERP_WORKSPACE_SUBJECT_RELATIONS_MAP,
    ERP_WORKSPACE_SUBJECT_PERMISSIONS_MAP,
  );
